---

- name: "BASE CONFIGURE REPGMR"
  ansible.builtin.include_tasks: "base/repmgr.yml"

- name: "BASE CONFIGURE SWAPPINESS"
  ansible.builtin.include_tasks: "base/swappiness.yml"

- name: "BASE CONFIGURE REPHACHECK"
  ansible.builtin.include_tasks: "base/rephacheck.yml"

- name: "BASE CONFIGURE FIREWALL RULES"
- ansible.builtin.import_role:
    name: "nudgis/shared"
    tasks_from: "firewall_rules_files.yml"
  vars:
    firewall_rules_files: "{{ repmgr_firewall_rules_files }}"

- name: "Flush handlers"
  ansible.builtin.meta: flush_handlers

...
