---

- name: "Reload systemd"
  ansible.builtin.systemd:
    daemon_reload: true

- name: "Restart sshd"
  ansible.builtin.systemd:
    name: sshd
    state: restarted

- name: "Restart pure-ftpd"
  ansible.builtin.systemd:
    name: pure-ftpd
    state: restarted

- name: "Restart mysecureshell"
  ansible.builtin.systemd:
    name: mysecureshell
    state: restarted

- name: "Restart mediaimport"
  ansible.builtin.systemd:
    name: ubicast-mediaimport
    state: restarted

- name: "Restart fail2ban"
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted

- ansible.builtin.import_tasks: ../../shared/handlers/nftables.yml

...
