#!/usr/bin/env ansible-playbook
---

- name: "NUDGIS VAULT"
  hosts: vault
  roles:
    - nudgis/vault
  post_tasks:
    - name: "Configure proxy"
      when: proxy_apply | d(false)
      ansible.builtin.include_role:
        name: system/proxy

...
