---
- name: LIVE
  hosts: live
  gather_facts: false
  tags: live
  roles:
    - live

- import_playbook: subplays/standard-case.yml
  when: groups['live'] | d('') | length >= 1 and ( hostvars[groups['live'][0]].ip_live is undefined or hostvars[groups['live'][0]].ip_live == "127.0.0.1" )

- import_playbook: subplays/ha-case.yml
  when: groups['live'] | d('') | length >= 1 and ( hostvars[groups['live'][0]].ip_live is defined and hostvars[groups['live'][0]].ip_live != "127.0.0.1" )
