---

- name: LIVE
  hosts: live
  tags: live
  roles:
    - base

# FIREWALL

- hosts: live
  tags: live
  vars:
    live_ferm_rules_filename: live
    live_ferm_input_rules:
      - proto:
          - tcp
        dport:
          - 80
          - 443
          - 1935
    live_ferm_output_rules: []
    live_ferm_global_settings:
  tasks:
    - name: firewall
      vars:
        ferm_rules_filename: "{{ live_ferm_rules_filename }}"
        ferm_input_rules: "{{ live_ferm_input_rules }}"
        ferm_output_rules: "{{ live_ferm_output_rules }}"
        ferm_global_settings: "{{ live_ferm_global_settings }}"
      ansible.builtin.include_role:
        name: ferm-configure

- import_playbook: deploy-minimal.yml
  tags: live

...
