---

- name: LIVE
  hosts: live
  gather_facts: false
  tags: live
  roles:
    - live

- import_playbook: subplays/standard-case.yml
  # playbook target mediaserver and live hosts
  when: groups['live'] | d('') | length >= 1 and ( hostvars[groups['live'][0]].live_ha is undefined or hostvars[groups['live'][0]].live_ha == false )

- import_playbook: subplays/ha-case.yml
  # playbook target mediaserver and live hosts
  when: groups['live'] | d('') | length >= 1 and ( hostvars[groups['live'][0]].live_ha is defined and hostvars[groups['live'][0]].live_ha == true )

...
