# Configuration file for installation and post installation scripts.
# IMPORTANT:
# This file must be readable ONLY by root to avoid revealing passwords.
# After any change, please reinstall the package to trigger the reconfiguration.

[conf]
# Domain to use for the application.
# This setting is used to replace the default domain "webmonitor" when
# the post-installation scripts are triggered.
# DOMAIN = monitor.example.com

# Administrator account (admin) password.
# The account password is applied when the post-installation scripts are triggered.
# If no value is set, the account will not be able to log in.
# ADMIN_PWD =
