#!/usr/bin/env ansible-playbook
---

- name: MEDIACACHE
  hosts: mediacache
  tags: mediacache
  roles:
    - base

# FIREWALL

- hosts: mediacache
  tags: mediacache
  vars:
    cache_ferm_rules_filename: mediacache
    cache_ferm_input_rules:
      - proto:
          - tcp
        dport:
          - 80
          - 443
    cache_ferm_output_rules: []
    cache_ferm_global_settings:
  tasks:
    - name: firewall
      vars:
        ferm_rules_filename: "{{ cache_ferm_rules_filename }}"
        ferm_input_rules: "{{ cache_ferm_input_rules }}"
        ferm_output_rules: "{{ cache_ferm_output_rules }}"
        ferm_global_settings: "{{ cache_ferm_global_settings }}"
      ansible.builtin.include_role:
        name: ferm-configure

- import_playbook: deploy-minimal.yml
  tags: mediacache

...
