---
network_apply: false

network_packages:
  - cockpit
  - libnm-dev
  - network-manager
  - python3-dbus
  - python3-gi

network_ip: "{{ envsetup_network_ip | d() }}"
network_mask: "{{ envsetup_network_mask | d() }}"
network_ip_mask: "{{ network_ip }}/{{ network_mask }}"
network_ip_mask_cidr: "{{ network_ip_mask | ipaddr }}"
network_gateway: "{{ envsetup_network_gateway | d() }}"
network_dns: "{{ envsetup_network_dns.split(',') | d() }}"
