---

- name: "Configure email sender address"
  notify: "Restart ubicast-skyreach"
  ansible.builtin.lineinfile:
    path: /var/lib/ubicast-skyreach/private/settings_override.py
    regexp: ^#? ?DEFAULT_FROM_EMAIL.*
    line: DEFAULT_FROM_EMAIL = '{{ manager_email_from }}'
    backup: true

...
