---

- name: "Create user group - {{ user }}"
  ansible.builtin.group:
    name: "{{ user }}"
    state: present

- name: "Create user - {{ user }}"
  ansible.builtin.user:
    name: "{{ user }}"
    group: "{{ user }}"
    shell: /bin/bash
    generate_ssh_key: true
    ssh_key_type: ed25519
    ssh_key_file: .ssh/id_ed25519
    append: true
    groups:
      - sudo
    state: present

- name: "Set password - {{ user }}"
  ansible.builtin.user:
    name: "{{ user }}"
    password: "{{ lookup('vars', 'sysuser_' + user + '_password') | password_hash('sha512', 'ubicastsalt') }}"
    update_password: always

- name: "SETUP DOTFILES - {{ user | upper }}"
  ansible.builtin.include_tasks: "../common/dotfiles.yml"

...
