---

- name: "Configure custom settings"
  notify: "Restart postgresql"
  when: item.content | d(false)
  ansible.builtin.copy:
    dest: "{{ database_conf_dir }}/conf.d/{{ item.name }}.conf"
    owner: postgres
    group: postgres
    backup: true
    content: "{{ item.content }}"
    mode: "644"
  loop: "{{ database_conf }}"

...
