---

nudgis_front_packages:
  - postgresql-client
  - cron
  - memcached
  - nginx
  - postfix
  - ubicast-mediaserver
  - rsync  # used for HA only (copy of instance data)

firewall_rules_files: ['http']

...
