---

- name: "INSTALL"
  ansible.builtin.include_tasks:
    file: "install.yml"
    apply:
      tags:
        - install
  tags:
    - always

- name: "CONFIGURE"
  ansible.builtin.include_tasks:
    file: "configure.yml"
    apply:
      tags:
        - configure
  tags:
    - always

...
