---

- name: "LIVE"
  hosts: live
  gather_facts: false
  roles:
    - nudgis/live

- import_playbook: subplays/standard-case.yml
  # playbook target mediaserver and live hosts
  when:
    - groups['live'] | default([]) | length >= 1
    - hostvars[groups['live'][0]]['live_ha'] | default(false) | bool == false
  tags: configure

- import_playbook: subplays/ha-case.yml
  # playbook target mediaserver and live hosts
  when:
    - groups['live'] | default([]) | length >= 1
    - hostvars[groups['live'][0]]['live_ha'] is defined
    - hostvars[groups['live'][0]]['live_ha'] == true
  tags: configure

...
