---

driver:
  name: docker

platforms:
  - name: ms-${CI_PIPELINE_ID:-default}
    environment:
      HOSTALIASES: /etc/hosts.aliases
    image: registry.ubicast.net/docker/debian-systemd:latest
    command: /lib/systemd/systemd
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /tmp
      - /run
    groups:
      - mediaserver
      - postgres
      - celerity
      - live
      - mirismanager
      - mediaimport
      - msmonitor
  - name: mw-${CI_PIPELINE_ID:-default}
    environment:
      HOSTALIASES: /etc/hosts.aliases
    image: registry.ubicast.net/docker/debian-systemd:latest
    command: /lib/systemd/systemd
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /tmp
      - /run
    groups:
      - mediaworker

provisioner:
  name: ansible
  options:
    D: true
  env:
    ANSIBLE_ROLES_PATH: ../../roles
    ANSIBLE_LIBRARY: ../../library
    ANSIBLE_ACTION_PLUGINS: ../../plugins/action
    ANSIBLE_PYTHON_INTERPRETER: /usr/bin/python3
    SKYREACH_SYSTEM_KEY: ${SKYREACH_SYSTEM_KEY_STD}

verifier:
  name: testinfra
  options:
    verbose: true

...
