---
manager_domain: "manager.example.com"
manager_email_from: "noreply@{{ manager_domain }}"
proxy_http: ""

manager_database_domain: "database.manager.example.com"
manager_database_port: "5432"
manager_database_password: "changeit"

manager_user_ubicast_password: "changeit"
manager_user_admin_password: "changeit"
...
