---

- name: fetch ssh public key
  register: root_ssh_pubkey
  ansible.builtin.slurp:
    path: /root/.ssh/id_ed25519.pub
  tags: always

- name: register ssh public key as an ansible fact
  ansible.builtin.set_fact:
    pubkey: "{{ root_ssh_pubkey['content'] | b64decode }}"
  tags: always

- name: share ssh public key between cluster members
  loop: "{{ groups['mediaserver'] }}"
  ansible.posix.authorized_key:
    user: root
    key: "{{ hostvars[item]['pubkey'] }}"
  tags: always

- name: synchronize configuration between servers # noqa command-instead-of-module
  # Cannot use the ansible synchronization module, cause there is no way to set a destination IP intead of the destination ansible hostname
  # noqa command-instead-of-module = warn to use the synchronization module instead of rsync in the command module
  when:
    - inventory_hostname != groups['mediaserver'][0]
  loop:
    - /etc/mediaserver
    - /etc/nginx
    - /etc/sysusers.d
    - /var/www
  ansible.builtin.command: |
    rsync \
      -avh \
      -e "ssh -o StrictHostKeyChecking=no" \
      --delete \
      "{{ item }}/" \
      "root@{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ item }}/"
  notify:
    - restart systemd-sysusers
    - restart nginx
    - restart mediaserver
  delegate_to: "{{ groups['mediaserver'][0] }}"
  changed_when: false
  tags: mediaserver-synchronize

- name: synchronize letsencrypt configuration between servers # noqa command-instead-of-module
  # Cannot use the ansible synchronization module, cause there is no way to set a destination IP intead of the destination ansible hostname
  # noqa command-instead-of-module = warn to use the synchronization module instead of rsync in the command module
  when:
    - inventory_hostname != groups['mediaserver'][0]
    - letsencrypt_enabled | d(false)
  loop:
    - /etc/letsencrypt
  ansible.builtin.command: |
    rsync \
      -avh \
      -e "ssh -o StrictHostKeyChecking=no" \
      --delete \
      "{{ item }}/" \
      "root@{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ item }}/"
  notify:
    - restart nginx
  delegate_to: "{{ groups['mediaserver'][0] }}"
  changed_when: false
  tags: mediaserver-synchronize

...
