---
- name: mirismanager dependencies install
  ansible.builtin.apt:
    force_apt_get: true
    install_recommends: false
    name: "{{ dependencies_packages }}"
  register: apt_status
  retries: 60
  until: apt_status is success or ('Failed to lock apt for exclusive operation' not in apt_status.msg and '/var/lib/dpkg/lock' not in apt_status.msg)

- name: start postgresql
  ansible.builtin.systemd:
    name: postgresql
    state: started

- name: mirismanager install
  ansible.builtin.apt:
    force_apt_get: true
    install_recommends: false
    name: "{{ manager_packages }}"
  register: apt_status
  retries: 60
  until: apt_status is success or ('Failed to lock apt for exclusive operation' not in apt_status.msg and '/var/lib/dpkg/lock' not in apt_status.msg)

- name: configure email sender address in settings
  notify: restart skyreach
  ansible.builtin.lineinfile:
    path: /home/skyreach/skyreach_data/private/settings_override.py
    regexp: ^#? ?DEFAULT_FROM_EMAIL.*
    line: DEFAULT_FROM_EMAIL = '{{ manager_email_sender }}'
    backup: true

- name: ensure skyreach is running
  ansible.builtin.service:
    name: skyreach
    enabled: true
    state: started

- name: check apt cacher ng config exists
  register: manager_apt_cacher_conf
  ansible.builtin.stat:
    path: /etc/apt-cacher-ng/acng.conf

- name: configure apt-cacher-ng
  when:
    - manager_apt_cacher_conf.stat.exists
    - manager_proxy_http | d(false)
  notify: restart apt-cacher-ng
  ansible.builtin.lineinfile:
    path: /etc/apt-cacher-ng/acng.conf
    regexp: "^Proxy: .*"
    line: "Proxy: {{ manager_proxy_http }}"

- name: ensure apt-cacher-ng is running
  ansible.builtin.service:
    name: apt-cacher-ng
    enabled: true
    state: started

# FIREWALL

- name: firewall
  when: manager_firewall_enabled
  vars:
    ferm_rules_filename: "{{ manager_ferm_rules_filename }}"
    ferm_input_rules: "{{ manager_ferm_input_rules }}"
    ferm_output_rules: "{{ manager_ferm_output_rules }}"
    ferm_global_settings: "{{ manager_ferm_global_settings }}"
  ansible.builtin.include_role:
    name: ferm-configure

- name: flush handlers
  ansible.builtin.meta: flush_handlers
