---

- name: CONFIGURE CELERITY
  ansible.builtin.include_tasks: "configure/celerity-conf.yml"
  when:
    - nudgis_front_api_key is defined
    - nudgis_front_domain is defined
    - celerity_server_domain is defined
    - celerity_signing_key is defined

...
