---

- name: "Install ssh packages"
  ansible.builtin.import_role:
    name: "nudgis/shared"
    tasks_from: "apt_install.yml"
  vars:
    apt_packages: "{{ ssh_packages }}"

- name: "Install UbiCast ssh public keys"
  when: not offline_mode | d(false)
  ansible.builtin.import_role:
    name: "nudgis/shared"
    tasks_from: "apt_install.yml"
  vars:
    apt_update_cache: true
    apt_packages: "{{ ssh_keys_packages }}"

...
