---
celerity_signing_key: "changeit"
celerity_server_domain: "celerity.example.com"

nudgis_front_domain: "nudgis.example.com"
nudgis_front_api_key: "XXXXX-XXXXX-XXXXX-XXXXX-XXXXX"
nudgis_front_system_user: "msuser"
...
