---

- name: "Restart nginx"
  ansible.builtin.service:
    name: nginx
    state: restarted

- name: "Restart skyreach"
  ansible.builtin.service:
    name: skyreach
    state: restarted

- name: "Restart apt-cacher-ng"
  ansible.builtin.service:
    name: apt-cacher-ng
    state: restarted

- ansible.builtin.import_tasks: ../../shared/handlers/nftables.yml

...
