---
- name: install packages
  ansible.builtin.package:
    force_apt_get: true
    install_recommends: false
    name: "{{ mediaimport_packages }}"

## MEDIAIMPORT

- name: enable password login for ssh
  notify: restart sshd
  ansible.builtin.replace:
    dest: /etc/ssh/sshd_config
    regexp: ^PasswordAuthentication no
    replace: "#PasswordAuthentication yes"

- name: enable mediaimport service
  ansible.builtin.systemd:
    name: mediaimport
    enabled: true

- name: enable mediaimport-cleanup timer
  ansible.builtin.systemd:
    name: mediaimport-cleanup.timer
    enabled: true

- name: configure mediaimport admin emails
  when:
    - envsetup_email_admins | d(false)
  notify: restart mediaimport
  ansible.builtin.template:
    src: mediaimport.json.j2
    dest: /etc/mediaserver/mediaimport.json
    backup: true
    mode: 0640

# FAIL2BAN

- name: deploy fail2ban jail
  notify: restart fail2ban
  ansible.builtin.template:
    src: fail2ban_ftpd.conf.j2
    dest: /etc/fail2ban/jail.d/pure-ftpd.conf
    mode: 0644

- name: flush handlers
  ansible.builtin.meta: flush_handlers

# FIREWALL

- name: firewall
  when: mediaimport_firewall_enabled
  vars:
    ferm_rules_filename: "{{ mediaimport_ferm_rules_filename }}"
    ferm_input_rules: "{{ mediaimport_ferm_input_rules }}"
    ferm_output_rules: "{{ mediaimport_ferm_output_rules }}"
    ferm_global_settings: "{{ mediaimport_ferm_global_settings }}"
  ansible.builtin.include_role:
    name: ferm-configure

- name: flush handlers
  ansible.builtin.meta: flush_handlers
