---

- name: "BASE CONFIGURE POSTGRESQL LOGROTATE"
  ansible.builtin.include_tasks: "base/logrotate.yml"

- ansible.builtin.import_role:
    name: "nudgis/shared"
    tasks_from: "firewall_rules_files.yml"
  vars:
    firewall_rules_files: "{{ database_firewall_rules_files }}"

- name: "Flush handlers"
  ansible.builtin.meta: flush_handlers

...
