---

# Configurartions files must stay here even without variables
# This role can be called from postgres_ha (with configure tag) with custom variables

- name: "CONFIGURE POSTGRESQL CUSTOM SETTINGS"
  ansible.builtin.include_tasks: "configure/custom-settings.yml"

- name: "CONFIGURE POSTGRESQL EXTERNAL AUTHENTICATIONS"
  ansible.builtin.include_tasks: "configure/authentication.yml"

- name: "CONFIGURE POSTGRESQL INTERNAL USERS"
  ansible.builtin.include_tasks: "configure/users.yml"
  when:
    - database_password is defined

- name: "CREATE POSTGRESQL DATABASES"
  ansible.builtin.include_tasks: "configure/databases.yml"

- name: "RESTRICT POSTGRESQSL CONFIGURATION RIGHTS"
  ansible.builtin.include_tasks: "configure/configuration-rights.yml"

# Flush to restart postgresql in time for HA deployment
- name: "Flush handlers"
  ansible.builtin.meta: flush_handlers

...
