---

vault_packages:
  - ubicast-mediavault

vault_email_service_name: "status-email-admin"
vault_email_service_path: "/etc/systemd/system/{{ vault_email_service_name }}@.service"
vault_email_script_path: "/usr/local/sbin/systemd-mailer"

...
