---

- name: verify systemd-timesyncd presence
  ansible.builtin.stat:
    path: /etc/systemd/timesyncd.conf
  register: timesyncd_config

- name: verify ntp variable
  when:
    - timesyncd_config.stat.exists
    - ntp_servers is defined
    - ntp_servers | type_debug == 'list'
    - ntp_servers | length > 0
  block:
    - name: configure systemd-timesyncd
      notify: restart ntp
      ansible.builtin.replace:
        path: /etc/systemd/timesyncd.conf
        regexp: '^(\s*)#?{{ item.name }}\s*=.*$'
        replace: '\1{{ item.name }}={{ item.value }}'
      loop:
        - { name: 'NTP', value: '{{ ntp_servers | join(" ") }}' }
      when:
        - item.value != ""
        - item.value != '""'

...
