---

- name: set timezone
  # in order to execute cron task at new set timezone
  # TODO: fix when there is no cron service
  # notify: restart cron
  notify: trigger dpkg-reconfigure tzdata
  community.general.timezone:
    name: "{{ init_timezone }}"

...
