---

- name: "Prepare the {{ sysconfig_repos_keyrings_dir }} directory"
  ansible.builtin.file:
    path: "{{ sysconfig_repos_keyrings_dir }}"
    state: directory
    mode: "755"

- name: "Add UbiCast repository public key"
  ansible.builtin.get_url:
    url: "https://{{ repos_ubicast_packages_domain }}/media/public.gpg"
    dest: "{{ sysconfig_repos_keyrings_dir }}/{{ repos_ubicast_packages_domain }}.asc"
    mode: "644"

- name: "Add UbiCast solutions repository"
  notify: trigger apt update
  ansible.builtin.deb822_repository:
    name: "ubicast"
    types: "deb"
    uris: "https://{{ repos_ubicast_packages_domain }}"
    suites: "packaging/apt/{{ repos_ubicast_packages_token }}/{{ repos_release }}/"
    signed_by: "{{ sysconfig_repos_keyrings_dir }}/{{ repos_ubicast_packages_domain }}.asc"

- name: "Add UbiCast security repository"
  notify: trigger apt update
  ansible.builtin.deb822_repository:
    name: "ubicast-security"
    types: "deb"
    uris: "https://{{ repos_ubicast_packages_domain }}"
    suites: "packaging/apt/ubicast-security-updates/{{ repos_release }}/"
    signed_by: "{{ sysconfig_repos_keyrings_dir }}/{{ repos_ubicast_packages_domain }}.asc"

- name: allow automatic updates for ubicast security repo
  ansible.builtin.lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    insertafter: ^Unattended-Upgrade::Origins-Pattern {$
    line: '        "origin=UbiCast,label=UbiCast-Security";'
    backup: true
  notify: restart unattended-upgrades

...
