---

- name: enable unattended upgrades
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "1";
    mode: "644"

- name: remove old kernel with unattended-upgrades
  ansible.builtin.replace:
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    regexp: ^//Unattended-Upgrade::Remove-Unused-Kernel-Packages.*$
    replace: Unattended-Upgrade::Remove-Unused-Kernel-Packages "true";
  notify: restart unattended-upgrades

...
