---

profile: basic  # min, basic, moderate, safety, shared, production

exclude_paths:
  - inventories/
  - .cache/
  - ${HOME}/.cache/

# Moved into the ".ansible-lint-ignore" file
skip_list:
  # Skip necessity to prefix role vars with role name
  - var-naming[no-role-prefix]
  # Roles should not be called with path, they should be foundable by ansible
  # To fix when considering packaging everything with ansible galaxy
  - role-name[path]
  # Some tasks and plays do not have names on purpose, to avoid excess of verbosity 
  - name[play]
  - name[missing]
  # To fix this would require implementing multiline comments in the variable generation scripts
  - yaml[line-length]

...
