---

profile: basic  # min, basic, moderate, safety, shared, production

exclude_paths:
  - inventories/
  - playbooks/bench-monitoring.yml
  - roles/bench-server
  - roles/bench-worker
  - roles/elastic
  - roles/metricbeat
  - roles/docker
  - .cache/
  - ${HOME}/.cache/

skip_list:
  - role-name                  # Skip role name pattern verification ("-" should not be used)
  - name[play]                 # Skip the rule dictating that all play should have a name
  - name[casing]               # Skip the rule dictating that all task name should begin with uppercase
  - name[template]             # Skip forcing to use jinja var at the end of a task name
  - var-naming[no-role-prefix] # Skip necessity to prefix role vars with role name

...
