---

exclude_paths:
  - .cache/
  - ${HOME}/.cache/

skip_list:
  - meta-no-info    # Skip warnings for missing galaxy_info in roles
  - role-name       # Skip role name pattern verification ("-" should not be used)
  - package-latest  # Skip warning when package installation state is set to latest

...
