---

extends: default

ignore: |
  .venv/
  roles/elastic.elasticsearch/

rules:
  braces:
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 0
    min-spaces-inside: 1
    max-spaces-inside: 1
    level: error
  brackets:
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 0
    min-spaces-inside: 1
    max-spaces-inside: 1
    level: error
  truthy:
    level: error
  line-length: disable
  indentation:
    spaces: consistent
    indent-sequences: true
    check-multi-line-strings: false
...
