---

- name: setup witness
  when: >
    (database_role is defined and database_role == "witness") or
    (database_role is undefined and inventory_hostname == groups['postgres'][2]) or
    (database_role is defined and database_role == "" and inventory_hostname == groups['postgres'][2])
  block:
    - name: check if witness already joined
      become: true
      become_user: postgres
      register: repmgr_check_witness
      community.general.postgresql_query:
        db: repmgr
        query: SELECT 1 FROM pg_tables WHERE tablename='nodes'

    - name: register witness
      become: true
      become_user: postgres
      changed_when: true
      when: repmgr_check_witness.query_result | length == 0
      notify: restart repmgrd
      ansible.builtin.command:
        cmd: repmgr --config-file={{ repmgr_conf_file }} --host={{ repmgr_primary_node }} witness register

- ansible.builtin.meta: flush_handlers # noqa name[missing]

...
