---

- name: "Enable password login for ssh"
  notify: "Restart sshd"
  ansible.builtin.replace:
    dest: /etc/ssh/sshd_config
    regexp: ^PasswordAuthentication no
    replace: "#PasswordAuthentication yes"

# mediaimport service failed without any account configured
- name: "Disable mediaimport service"
  ansible.builtin.systemd:
    name: mediaimport
    enabled: false

- name: "Enable mediaimport-cleanup timer"
  ansible.builtin.systemd:
    name: mediaimport-cleanup.timer
    enabled: true

- name: "Configure mediaimport admin emails"
  when:
    - import_email_to | d(false)
  notify: "Restart mediaimport"
  ansible.builtin.template:
    src: mediaimport.json.j2
    dest: /etc/mediaimport/mediaimport.json
    backup: true
    mode: "0600"

# FAIL2BAN

- name: "Deploy fail2ban pure-ftpd jail"
  notify: "Restart fail2ban"
  ansible.builtin.copy:
    dest: /etc/fail2ban/jail.d/pure-ftpd.conf
    mode: "0644"
    content: |
      [pure-ftpd]
      enabled = true

- name: "Configure pure-ftpd jail backend"
  notify: "Restart fail2ban"
  ansible.builtin.lineinfile:
    path: /etc/fail2ban/paths-overrides.local
    regexp: '^pureftpd_backend'
    insertafter: '[DEFAULT]'
    line: 'pureftpd_backend = systemd'

- name: "Flush handlers"
  ansible.builtin.meta: flush_handlers

# FIREWALL

- ansible.builtin.import_tasks: ../../shared/tasks/firewall_rules_files.yml

- name: "Flush handlers"
  ansible.builtin.meta: flush_handlers

...
