---

- name: restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted

- name: restart mediaserver
  ansible.builtin.systemd:
    name: mediaserver
    state: restarted

- name: restart systemd-sysusers
  ansible.builtin.systemd:
    name: systemd-sysusers
    state: restarted

- import_tasks: ../../shared/handlers/munin-node.yml  # noqa: name[missing]
- import_tasks: ../../shared/handlers/nftables.yml  # noqa: name[missing]

...
