---

- name: mscontroller restart
  ansible.builtin.command:
    cmd: mscontroller.py restart

- name: restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted

- name: restart mediaserver
  ansible.builtin.systemd:
    name: mediaserver
    state: restarted

- name: restart systemd-sysusers
  ansible.builtin.systemd:
    name: systemd-sysusers
    state: restarted

...
