---

- name: "Update apt cache"
  ansible.builtin.apt:
    update_cache: true
  changed_when: false
  register: apt_status
  retries: 60
  until: apt_status is success or ('Failed to lock apt for exclusive operation' not in apt_status.msg and '/var/lib/dpkg/lock' not in apt_status.msg)

- name: "Install repository utilities"
  ansible.builtin.import_role:
    name: "nudgis/shared"
    tasks_from: "apt_install.yml"
  vars:
    apt_packages: "{{ sysconfig_repos_packages }}"

...
