---

- name: "Update apt cache"
  ansible.builtin.include_tasks: "base/apt_force_update.yml"

- name: "Install repository utilities"
  ansible.builtin.import_role:
    name: "nudgis/shared"
    tasks_from: "apt_install.yml"
  vars:
    apt_update_cache: true
    apt_packages: "{{ sysconfig_repos_packages }}"

...
