---

- name: "Update apt cache"
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 86400
  changed_when: false
  register: apt_status
  retries: 60
  until: apt_status is success or ('Failed to lock apt for exclusive operation' not in apt_status.msg and '/var/lib/dpkg/lock' not in apt_status.msg)

- name: "Install repository utilities"
  ansible.builtin.apt:
    force_apt_get: true
    install_recommends: false
    name: "{{ sysconfig_repos_packages }}"
    state: present
  register: apt_status
  retries: 60
  until: apt_status is success or ('Failed to lock apt for exclusive operation' not in apt_status.msg and '/var/lib/dpkg/lock' not in apt_status.msg)

...
