---

# This task should always be executed
#  - with install and base for OVA images
#  - with configure for customer configuration
- name: "INSTALL"
  ansible.builtin.include_tasks:
    file: "install.yml"
    apply:
      tags:
        - always
  tags:
    - always

- name: "BASE CONFIGURATION"
  ansible.builtin.include_tasks:
    file: "base.yml"
    apply:
      tags:
        - always
  tags:
    - always

...
