---
cache_domain: "cache.example.com"
nudgis_front_domain: "nudgis.example.com"
live_domain: "nudgis.example.com"

# MediaCache data folder - for VOD
cache_vod_folder: "/var/cache/nginx/mediacache-vod"
# MediaCache size in Gb - for VOD
cache_vod_size: "1"

# MediaCache data folder - for live
cache_live_folder: "/var/cache/nginx/mediacache-live"
# MediaCache size in Gb - for live
cache_live_size: "1"
...
