---

# MediaCache data folder - for VOD
role_mc_vod_folder: "{{ mediacache_vod_folder | d('/var/cache/nginx/mediacache-vod') }}"
# MediaCache size in Gb - for VOD
role_mc_vod_size: "{{ mediacache_vod_size }}"

# MediaCache data folder - for live
role_mc_live_folder: "{{ mediacache_live_folder | d('/var/cache/nginx/mediacache-live') }}"
# MediaCache size in Gb - for live
role_mc_live_size: "{{ mediacache_live_size | d('1') }}"

...
