---

# Define if the deployment is an HA architecture (i.e. live domain is not handle by nudgis frontend server)
live_ha: false

# Domain name of the live cluster (only if distinct live server(s) from MediaServer and live_ha variable is set to True)
live_domain: "live.example.com"

# Size of the tmpfs storing the live chunks (unit g or m and only if distinct live server(s) from MediaServer)
live_tmpfs_size: "2048m"

...
