---

# Packages required for the group. ssl-cert is used for optionnal FTPS support
import_packages:
  - ssl-cert
  - ubicast-mediaimport

# Group firewall rules filename, see roles/shared/files/nftables/
firewall_rules_files:
  - ftp

...
