---

import_packages:
  - ssl-cert # for optionnal FTPS support (the mediaimport postinst will will use the snakeoil certificate for pure-ftpd)
  - ubicast-mediaimport

firewall_rules_files: ['ftp']

...
