#!/usr/bin/env ansible-playbook
---
- name: REPMGRD RESTART
  hosts: postgres
  tasks:
    - name: kill repmgrd
      command: "pkill repmgrd"
      # TOFIX: implement a proper verification
      changed_when: false
      failed_when: false

    - name: restart repmgrd
      systemd:
        name: repmgrd
        state: restarted

...
