---

offline_mode: false

repos_release: "{{ ansible_distribution_release }}"
repos_ubicast_packages_domain: "manager.example.com"
repos_ubicast_packages_token: "XXXX-XXXX-XXXX-XXXX-XXXX"

init_locale: 'en_GB.UTF-8'
init_timezone: "Europe/Paris"

ntp_servers: "0.pool.ntp.org,1.pool.ntp.org,2.pool.ntp.org,3.pool.ntp.org"

...
