---

- name: create mediacache live data directory
  ansible.builtin.file:
    dest: "{{ cache_live_folder }}"
    state: directory
    owner: nginx
    group: root
    mode: "0700"
  when: live_domain is defined

- name: fill the mediacache zones file - Live folder
  notify: restart nginx
  ansible.builtin.replace:
    path: /etc/mediacache/nginx-zones.conf
    regexp: /var/cache/nginx/mediacache-live
    replace: "{{ cache_live_folder }}"

- name: fill the mediacache zones file - Live folder size
  notify: restart nginx
  ansible.builtin.replace:
    path: /etc/mediacache/nginx-zones.conf
    regexp: (?P<key>keys_zone=mediacache-live.*max_size=).*(?P<unit>g)
    replace: \g<key>{{ cache_live_size }}\g<unit>

...
