---

- name: create mediacache VOD data directory
  ansible.builtin.file:
    dest: "{{ cache_vod_folder }}"
    state: directory
    owner: nginx
    group: root
    mode: "0700"

- name: fill the mediacache zones file - VOD folder
  notify: restart nginx
  ansible.builtin.replace:
    path: /etc/mediacache/nginx-zones.conf
    regexp: /var/cache/nginx/mediacache-vod
    replace: "{{ cache_vod_folder }}"

- name: fill the mediacache zones file - VOD folder size
  notify: restart nginx
  ansible.builtin.replace:
    path: /etc/mediacache/nginx-zones.conf
    regexp: (?P<key>keys_zone=mediacache-vod.*max_size=).*(?P<unit>g)
    replace: \g<key>{{ cache_vod_size }}\g<unit>

...
