---

- name: "Copy celerity example configuration"
  notify: "Restart celerity-server"
  ansible.builtin.copy:
    remote_src: true
    src: /etc/celerity/config.example.py
    dest: /etc/celerity/config.py
    mode: preserve
    force: false

- name: "Celerity base configuration"
  notify: "Restart celerity-server"
  ansible.builtin.replace:
    path: /etc/celerity/config.py
    regexp: '^(\s*)#?{{ item.name }}\s*=.*$'
    replace: '\1{{ item.name }} = {{ item.value }}'
  loop:
    - { name: 'SERVER_URL', value: '"https://{{ celerity_server_domain }}:6200"' }
    - { name: 'SIGNING_KEY', value: '"{{ celerity_signing_key }}"' }
  when: item.value != "" and item.value != '""'

- name: "Celerity add nudgis portal"
  notify: "Restart celerity-server"
  ansible.builtin.command:
    cmd: >
      celerity-configurator add-portal
        'ms_id=1_{{ nudgis_front_system_user }}'
        'url=https://{{ nudgis_front_domain }}'
        'api_key={{ nudgis_front_api_key }}'
  register: celerity_add_portal
  changed_when: celerity_add_portal['stdout'] != 'The configuration file is already up to date.'

- name: "Ensure celerity-server is running"
  ansible.builtin.service:
    name: "celerity-server"
    enabled: true
    state: started

...
