---
- import_playbook: ../functions/create-live-app.yml
  vars:
    live_app_name: msuser
    rtmp_hls_url: https://%(ms_host)s/streaming-rtmp/%(stream_id)s.m3u8
    rtmp_pub_url: rtmp://%(ms_host)s/%(rtmp_app)s/%(stream_id)s
    deploy_case: standard
