---

- name: ensure /etc/mediaserver directory exist
  ansible.builtin.file:
    path: /etc/mediaserver
    state: directory
    mode: "755"  # use mediaserver package post-install rights...
- name: copy mediaserver install.ini file from sample
  ansible.builtin.copy:
    src: install.example.ini
    dest: /etc/mediaserver/install.ini
    force: false
    mode: "640"  # use mediaserver package post-install rights...

- name: prepare mediaserver variables in install.ini file
  ansible.builtin.replace:
    path: /etc/mediaserver/install.ini
    regexp: '^(\s*)#?\s*{{ item.name }}\s*=.*$'
    replace: '\1{{ item.name }} = {{ item.value }}'
  loop:
    - { name: 'DB_HOST',       value: '{{ nudgis_front_database_domain }}' }   # noqa: yaml[commas]
    - { name: 'DB_PORT',       value: '{{ nudgis_front_database_port }}' }     # noqa: yaml[commas]
    - { name: 'DB_ROOT_PWD',   value: '{{ nudgis_front_database_password }}' } # noqa: yaml[commas]
    - { name: 'DATA_NEW_DIRS', value: '{{ nudgis_front_instances_dir }}' }     # noqa: yaml[commas]
    - { name: 'DATA_DIRS',     value: '{{ nudgis_front_instances_dir }}' }     # noqa: yaml[commas]
  when: item.value != "" and item.value != '""'

- name: mediaserver install
  ansible.builtin.apt:
    force_apt_get: true
    install_recommends: false
    name: "{{ nudgis_front_packages }}"
  register: apt_status
  retries: 60
  until: apt_status is success or ('Failed to lock apt for exclusive operation' not in apt_status.msg and '/var/lib/dpkg/lock' not in apt_status.msg)

- name: fetch ssh public key
  register: root_ssh_pubkey
  ansible.builtin.slurp:
    path: /root/.ssh/id_ed25519.pub
  tags: always

- name: register ssh public key as an ansible fact
  ansible.builtin.set_fact:
    pubkey: "{{ root_ssh_pubkey['content'] | b64decode }}"
  tags: always

- name: share ssh public key between cluster members
  loop: "{{ groups['mediaserver'] }}"
  ansible.posix.authorized_key:
    user: root
    key: "{{ hostvars[item]['pubkey'] }}"
  tags: always

- name: Update the MS configuration with the celerity server IP
  ansible.builtin.lineinfile:
    path: /etc/mediaserver/msconf.py
    regexp: "^CELERITY_SERVER_URL = "
    line: CELERITY_SERVER_URL = 'https://{{ celerity_server_domain }}:6200'
    create: true
    owner: root
    group: root
    # 644 as all the instances must reach this file
    # The instances cannot be in a common group as of now => https://redmine.ubicast.net/issues/33046
    mode: "0644"

- name: Update the MS configuration with the celerity server secret
  ansible.builtin.lineinfile:
    path: /etc/mediaserver/msconf.py
    regexp: "^CELERITY_SIGNING_KEY = "
    line: CELERITY_SIGNING_KEY = '{{ celerity_signing_key }}'
    create: true
    owner: root
    group: root
    # 644 as all the instances must reach this file
    # The instances cannot be in a common group as of now => https://redmine.ubicast.net/issues/33046
    mode: "0644"

- name: create instance
  ansible.builtin.command:
    cmd: >
      mscontroller.py add -u "{{ nudgis_front_system_user }}" -t '{
        "id": "1_{{ nudgis_front_system_user }}",
        "domain": "{{ nudgis_front_domain }}",
        "api_key": "{{ nudgis_front_api_key }}",
        "superuser_pwd": "{{ nudgis_front_user_ubicast_password }}",
        "admin_pwd": "{{ nudgis_front_user_admin_password }}",
        "skyreach_url": "{{ manager_domain }}"
      }'
    creates: "/etc/nginx/sites-available/mediaserver-{{ nudgis_front_system_user }}.conf"
  throttle: 1

- name: synchronize configuration between servers # noqa command-instead-of-module
  # Cannot use the ansible synchronization module, cause there is no way to set a destination IP intead of the destination ansible hostname
  # noqa command-instead-of-module = warn to use the synchronization module instead of rsync in the command module
  when:
    - groups['mediaserver'] | length > 1
    - inventory_hostname != groups['mediaserver'][0]
  loop:
    - /etc/mediaserver
    - /etc/nginx
    - /etc/sysusers.d
    - /var/www
  ansible.builtin.command: |
    rsync \
      -avh \
      -e "ssh -o StrictHostKeyChecking=no" \
      --delete \
      "{{ item }}/" \
      "root@{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ item }}/"
  notify:
    - restart systemd-sysusers
    - restart nginx
    - restart mediaserver
  delegate_to: "{{ groups['mediaserver'][0] }}"
  changed_when: false
  tags: mediaserver-synchronize

- name: synchronize letsencrypt configuration between servers # noqa command-instead-of-module
  # Cannot use the ansible synchronization module, cause there is no way to set a destination IP intead of the destination ansible hostname
  # noqa command-instead-of-module = warn to use the synchronization module instead of rsync in the command module
  when:
    - groups['mediaserver'] | length > 1
    - inventory_hostname != groups['mediaserver'][0]
    - letsencrypt_enabled | d(false)
  loop:
    - /etc/letsencrypt
  ansible.builtin.command: |
    rsync \
      -avh \
      -e "ssh -o StrictHostKeyChecking=no" \
      --delete \
      "{{ item }}/" \
      "root@{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ item }}/"
  notify:
    - restart nginx
  delegate_to: "{{ groups['mediaserver'][0] }}"
  changed_when: false
  tags: mediaserver-synchronize

- name: configure email sender address
  notify:
    - restart mediaserver
  ansible.builtin.lineinfile:
    path: /etc/mediaserver/msconf.py
    backup: true
    create: true
    owner: root
    group: root
    # 644 as all the instances must reach this file
    # The instances cannot be in a common group as of now => https://redmine.ubicast.net/issues/33046
    mode: "0644"
    regexp: ^#? ?DEFAULT_FROM_EMAIL.*
    line: DEFAULT_FROM_EMAIL = '{{ nudgis_front_email_from }}'
    validate: python3 -m py_compile %s

- name: configure domain name in nginx conf
  notify: restart nginx
  ansible.builtin.replace:
    path: /etc/nginx/sites-available/mediaserver-{{ nudgis_front_system_user }}.conf
    regexp: ^(\s*server_name).*;$
    replace: \1 {{ nudgis_front_domain }};
    backup: true

- name: configure domain name in database
  ansible.builtin.shell:
    cmd: |
      python3 /usr/lib/python3/dist-packages/mediaserver/scripts/mssiteconfig.py {{ nudgis_front_system_user }} site_url=https://{{ nudgis_front_domain }} ;
      mscontroller.py restart -u {{ nudgis_front_system_user }} ;
      touch /etc/mediaserver/.{{ nudgis_front_domain }}.mssiteconfig.log ;
    creates: /etc/mediaserver/.{{ nudgis_front_domain }}.mssiteconfig.log

- name: reset service resources
  ansible.builtin.shell:
    cmd: |
      python3 /usr/lib/python3/dist-packages/mediaserver/scripts/reset_service_resources.py {{ nudgis_front_system_user }} local ;
      mscontroller.py restart -u {{ nudgis_front_system_user }} ;
      touch /etc/mediaserver/.{{ nudgis_front_domain }}.reset_service_resources.log ;
    creates: /etc/mediaserver/.{{ nudgis_front_domain }}.reset_service_resources.log

- name: ensure clamav-freshclam service is enabled and running
  ansible.builtin.service:
    name: clamav-freshclam
    enabled: true
    state: started

- name: ensure mediaserver is running
  ansible.builtin.service:
    name: mediaserver
    enabled: true
    state: started

# FIREWALL

- name: firewall
  vars:
    ferm_rules_filename: "{{ nudgis_front_ferm_rules_filename }}"
    ferm_input_rules: "{{ nudgis_front_ferm_input_rules }}"
    ferm_output_rules: "{{ nudgis_front_ferm_output_rules }}"
    ferm_global_settings: "{{ nudgis_front_ferm_output_global_settings }}"
  ansible.builtin.include_role:
    name: ferm-configure

- name: flush handlers
  ansible.builtin.meta: flush_handlers

...
