---

- name: MediaCache packages installation
  ansible.builtin.apt:
    force_apt_get: true
    install_recommends: false
    name: "{{ cache_packages }}"
    state: present
  register: apt_status
  retries: 60
  until: apt_status is success or ('Failed to lock apt for exclusive operation' not in apt_status.msg and '/var/lib/dpkg/lock' not in apt_status.msg)

- name: resolve domain name to localhost
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: 127.0.1.1 {{ cache_domain }}
    backup: true

- name: create mediacache VOD data directory
  ansible.builtin.file:
    dest: "{{ cache_vod_folder }}"
    state: directory
    owner: nginx
    group: root
    mode: "0700"

- name: create mediacache live data directory
  ansible.builtin.file:
    dest: "{{ cache_live_folder }}"
    state: directory
    owner: nginx
    group: root
    mode: "0700"
  when: live_domain is defined

- name: fill the vhost file
  notify: restart nginx
  ansible.builtin.replace:
    path: /etc/nginx/sites-available/mediacache.conf
    regexp: ^(\s+server_name)\s+.*(;)$
    replace: \1 {{ cache_domain }}\2

- name: fill the mediacache zones file - VOD folder
  notify: restart nginx
  ansible.builtin.replace:
    path: /etc/mediacache/nginx-zones.conf
    regexp: /var/cache/nginx/mediacache-vod
    replace: "{{ cache_vod_folder }}"

- name: fill the mediacache zones file - Live folder
  notify: restart nginx
  ansible.builtin.replace:
    path: /etc/mediacache/nginx-zones.conf
    regexp: /var/cache/nginx/mediacache-live
    replace: "{{ cache_live_folder }}"

- name: fill the mediacache zones file - VOD folder size
  notify: restart nginx
  ansible.builtin.replace:
    path: /etc/mediacache/nginx-zones.conf
    regexp: (?P<key>keys_zone=mediacache-vod.*max_size=).*(?P<unit>g)
    replace: \g<key>{{ cache_vod_size }}\g<unit>

- name: fill the mediacache zones file - Live folder size
  notify: restart nginx
  ansible.builtin.replace:
    path: /etc/mediacache/nginx-zones.conf
    regexp: (?P<key>keys_zone=mediacache-live.*max_size=).*(?P<unit>g)
    replace: \g<key>{{ cache_live_size }}\g<unit>

- name: fill the nginx VOD proxypass
  notify: restart nginx
  ansible.builtin.replace:
    path: /etc/mediacache/nginx-proxy-mediaserver.conf
    regexp: ^(proxy_pass)\s+.*(;)$
    replace: \1 https://{{ nudgis_front_domain }}\2

- name: fill the nginx Live proxypass
  notify: restart nginx
  ansible.builtin.replace:
    path: /etc/mediacache/nginx-proxy-live.conf
    regexp: ^(proxy_pass)\s+.*(;)$
    replace: \1 https://{{ live_domain }}\2

# FIREWALL

- name: firewall
  vars:
    ferm_rules_filename: "{{ cache_ferm_rules_filename }}"
    ferm_input_rules: "{{ cache_ferm_input_rules }}"
    ferm_output_rules: "{{ cache_ferm_output_rules }}"
    ferm_global_settings: "{{ cache_ferm_output_global_settings }}"
  ansible.builtin.include_role:
    name: ferm-configure

- name: flush handlers
  ansible.builtin.meta: flush_handlers

...
