---

- import_playbook: ../functions/create-live-app.yml
  vars:
    live_app_name: 'msuser'
    rtmp_hls_url: 'https://%(domain)s/streaming-rtmp/%(stream)s.m3u8'
    rtmp_pub_url: 'rtmp://%(domain)s/%(app)s/%(stream)s'
    deploy_case: 'standard'

...
