---

# UbiCast repository token used to make API call to mirismanager.ubicast.net to retrieve system informations
repos_ubicast_packages_token: "XXXX-XXXX-XXXX-XXXX-XXXX"

# UbiCast admin reciever of the email report for premiums
tester_email_admin: "sysadmin+premium@ubicast.eu"

# Sender of the email report
tester_email_from: "ubicast.tester"

# Reciever of the email report
tester_email_to: "example@example.com"

# List of tests to ignore when executing the ubicast-tester
tester_tests_ignored: []

...
