---
- name: install required packages for munin-server
  ansible.builtin.apt:
    force_apt_get: true
    install_recommends: false
    state: latest
    name:
      - munin
  register: apt_status
  retries: 60
  until: apt_status is success or ('Failed to lock apt for exclusive operation' not in apt_status.msg and '/var/lib/dpkg/lock' not in apt_status.msg)

- name: copy munin-server configuration
  notify: restart munin-server
  ansible.builtin.template:
    src: munin.conf.j2
    dest: /etc/munin/munin.conf
    mode: "644"

# Force munin-server restart to avoid default localdomain graph creation after remove
- name: flush handlers
  ansible.builtin.meta: flush_handlers

- name: remove default localdomain files
  ansible.builtin.file:
    path: /var/cache/munin/www/localdomain
    state: absent
