---

- name: Setup munin-node plugins link
  ansible.builtin.shell:
    munin-node-configure --shell --remove-also 2>&1 | sh -x  # noqa risky-shell-pipe
  # sh -x print executed cmd to stderr
  register: munin_plugin_linked
  changed_when: munin_plugin_linked.stderr | length > 0

- name: Restart munin-node service
  ansible.builtin.service:
    name: munin-node
    state: restarted

...
