---

- name: "Consolidate the no_proxy list"
  ansible.builtin.set_fact:
    proxy_no: "{{ (['localhost', '127.0.0.1', '::1'] + proxy_exclude) | join(',') }}"

- name: "Environment"
  ansible.builtin.blockinfile:
    path: /etc/environment
    create: true
    marker_begin: BEGIN PROXY
    marker_end: END PROXY
    mode: "644"
    block: |
      http_proxy={{ proxy_http }}
      HTTP_PROXY={{ proxy_http }}
      https_proxy={{ proxy_https }}
      HTTPS_PROXY={{ proxy_https }}
      no_proxy={{ proxy_no }}
      NO_PROXY={{ proxy_no }}

- name: "Configure proxy for apt"
  ansible.builtin.blockinfile:
    path: /etc/apt/apt.conf.d/proxy
    create: true
    marker_begin: BEGIN PROXY
    marker_end: END PROXY
    mode: "644"
    content: |
      Acquire::http::Proxy "{{ proxy_http }}";
      Acquire::https::Proxy "{{ proxy_https }}";

- name: "Gather the package facts"
  ansible.builtin.package_facts:
    manager: auto

- name: "Configure proxy for apt-cacher-ng"
  when: "'apt-cacher-ng' in ansible_facts.packages"
  notify: "Restart apt-cacher-ng"
  ansible.builtin.blockinfile:
    path: /etc/apt-cacher-ng/acng.conf
    marker_begin: BEGIN PROXY
    marker_end: END PROXY
    mode: "644"
    content: |
      Proxy: {{ proxy_http }}

- name: "Configure proxy for wget"
  when: "'wget' in ansible_facts.packages"
  ansible.builtin.blockinfile:
    path: /etc/wgetrc
    create: true
    marker_begin: BEGIN PROXY
    marker_end: END PROXY
    mode: "644"
    content: |
      use_proxy=yes
      http_proxy={{ proxy_http }}
      https_proxy={{ proxy_https }}
      no_proxy={{ proxy_no }}

- name: "Configure proxy for git"
  when: "'git' in ansible_facts.packages"
  community.general.git_config:
    name: "{{ item.name }}"
    scope: global
    value: "{{ item.value }}"
    state: present
  loop:
    - name: http.proxy
      value: "{{ proxy_http }}"
    - name: https.proxy
      value: "{{ proxy_https }}"

...
