---

# Proxy URL for HTTP calls (complete URL with protocol)
proxy_http: ""

# Proxy URL for HTTPS calls (complete URL with protocol)
proxy_https: ""

# List of URL that does not use the proxy
proxy_exclude:
  - localhost
  - 127.0.0.1
  - ::1
  - nudgis.example.com
  - manager.example.com
  - monitor.example.com

...
