---

- name: configure email sender address
  notify: restart skyreach
  ansible.builtin.lineinfile:
    path: /home/skyreach/skyreach_data/private/settings_override.py
    regexp: ^#? ?DEFAULT_FROM_EMAIL.*
    line: DEFAULT_FROM_EMAIL = '{{ manager_email_from }}'
    backup: true

...
