---

# ubicast-skyreach-runtime packages: todo: manage the database in inventory (/!\ can be idenpendent of the MS database)
dependencies_packages:
  - apt-cacher-ng
  - cron
  - nginx
  - postfix
  - postgresql

manager_packages:
  - ubicast-skyreach

firewall_rules_files: ['http', 'apt-cacher']

...
