---

- name: "Celerity server install"
  notify: "Reload fail2ban"
  ansible.builtin.import_role:
    name: "nudgis/shared"
    tasks_from: "apt_install.yml"
  vars:
    apt_packages: ["ubicast-celerity-server"]

...
