#!/usr/bin/env ansible-playbook
---

- name: "NUDGIS MANAGER"
  hosts: manager
  roles:
    - nudgis/manager
  post_tasks:
    - name: "Configure proxy"
      when: proxy_apply | d(false)
      ansible.builtin.include_role:
        name: system/proxy

...
