---

munin_node_packages:
  - munin-node
  - ubicast-munin

munin_node_logfile: /var/log/munin/munin_node.log
munin_node_pidfile: /var/run/munin/munin_node.pid

firewall_rules_files: ['munin-node']

...
