# Configuration file for installation and post installation scripts.
# IMPORTANT:
# This file must be readable ONLY by root to avoid revealing passwords.

[conf]
# Database host.
# Can be a hostname or an IP.
# DB_HOST = 127.0.0.1

# Database port.
# DB_PORT = 5432

# Database superuser account name.
# This account is used during deployments and upgrades.
# DB_ROOT_USER =

# Database superuser account password.
# This account is used during deployments and upgrades.
# DB_ROOT_PWD =

# Directories pattern for new instance creation.
# Can contain a glob part, for example: `/data/nas*`.
# DATA_NEW_DIRS = /data

# Directories pattern for existing instances.
# Can contain a glob part, for example: `/data/nas*`.
# DATA_DIRS = /data

