---

monitor_shell_pwd: "{{ envsetup_monitor_shell_pwd | d() }}"
monitor_admin_pwd: "{{ envsetup_monitor_admin_pwd | d() }}"
monitor_superuser_pwd: "{{ envsetup_monitor_superuser_pwd | d() }}"
ssh_maintenance_port: "{{ envsetup_ssh_maintenance_port | d() }}"
monitor_hostname: "{{ envsetup_monitor_server_name | d('monitor', true) }}"

monitor_firewall_enabled: true
monitor_ferm_rules_filename: monitor
monitor_ferm_input_rules:
  - proto:
      - tcp
    dport:
      - 80
      - 443
monitor_ferm_output_rules: []
monitor_ferm_global_settings:

...
