---

- name: restart postgresql
  ansible.builtin.systemd:
    name: postgresql@{{ database_version }}-{{ database_cluster }}
    state: restarted

- import_tasks: ../../shared/handlers/nftables.yml  # noqa: name[missing]

...
