---

- name: DEBIAN APT REPOSITORIES
  ansible.builtin.include_tasks: "base/apt_debian.yml"
  when:
    - offline_mode is defined and not offline_mode
    - repos_debian_prefix is defined
    - repos_debian_packages_domain is defined
    - repos_debian_security_packages_domain is defined

- name: UBICAST APT REPOSITORIES
  ansible.builtin.include_tasks: "base/apt_ubicast.yml"
  when:
    - offline_mode is defined and not offline_mode
    - repos_ubicast_packages_token is defined
    - repos_ubicast_packages_domain is defined

# Flush to force `apt update` with the news repositories
- name: Flush handlers
  meta: flush_handlers

- name: BASE CONFIGURE SSH CLIENT
  ansible.builtin.include_tasks: "base/ssh-client.yml"

- name: BASE CONFIGURE UNATTENDED-UPGRADES
  ansible.builtin.include_tasks: "base/unattended_upgrades.yml"

- name: BASE CONFIGURE SSH SERVER
  ansible.builtin.include_tasks: "base/ssh-server.yml"

- name: BASE CONFIURE PROMPT
  ansible.builtin.include_tasks: "base/prompt.yml"

- name: BASE CONFIGURE LOGS
  ansible.builtin.include_tasks: "base/logs.yml"

...
