---

- name: CONFIGURE PROXY
  ansible.builtin.include_tasks: "configure/proxy.yml"

- name: SYSTEM LOCALES
  ansible.builtin.include_tasks: "configure/locale.yml"
  when:
    - init_locale is defined

- name: SYSTEM TIMEZONE
  ansible.builtin.include_tasks: "configure/timezone.yml"
  when:
    - init_timezone is defined

- name: NTP
  ansible.builtin.include_tasks: "configure/ntp.yml"
  when:
    - ntp_servers is defined

# Flush to force `apt update` with the news repositories
- name: Flush handlers
  meta: flush_handlers

...
