---

- name: install locale packages
  ansible.builtin.apt:
    force_apt_get: true
    install_recommends: false
    name: "{{ locale_packages }}"
  register: apt_status
  retries: 60
  until: apt_status is success or ('Failed to lock apt for exclusive operation' not in apt_status.msg and '/var/lib/dpkg/lock' not in apt_status.msg)

- name: generate locale
  when: init_locale != 'C.UTF-8'
  community.general.locale_gen:
    name: "{{ init_locale }}"

- name: set locale
  notify: update locale
  ansible.builtin.copy:
    dest: /etc/default/locale
    mode: "644"
    content: |
      LANG={{ init_locale }}
      LANGUAGE={{ init_locale }}
      LC_ALL={{ init_locale }}

- name: set locale.gen
  notify: update locale
  ansible.builtin.lineinfile:
    path: /etc/locale.gen
    regexp: ^(?:# )?({{ init_locale }}.*)$
    backrefs: true
    line: \1

- name: set timezone (part.1)
  # in order to execute cron task at new set timezone
  # TODO: fix when there is no cron service
  # notify: restart cron
  community.general.timezone:
    name: "{{ init_timezone }}"

- name: set timezone (part.2)
  # https://unix.stackexchange.com/questions/451709/timedatectl-set-timezone-doesnt-update-etc-timezone
  # timedatectl do not update the /etc/timzone file...
  ansible.builtin.command:
    cmd: dpkg-reconfigure --frontend noninteractive tzdata
  changed_when: false

...
