---
- name: gathering services
  ansible.builtin.service_facts:
- name: ntp disable systemd-timesyncd service
  notify: restart ntp
  ansible.builtin.systemd:
    name: systemd-timesyncd
    enabled: false
    daemon_reload: true
    state: stopped
  when: ('systemd-timesyncd.service' in ansible_facts.services) and (ansible_facts.services['systemd-timesyncd.service'].status != 'not-found')

- name: ntp install
  ansible.builtin.apt:
    force_apt_get: true
    install_recommends: false
    name: ntp
    state: present
  register: apt_status
  retries: 60
  until: apt_status is success or ('Failed to lock apt for exclusive operation' not in apt_status.msg and '/var/lib/dpkg/lock' not in apt_status.msg)

- name: ntp config
  notify: restart ntp
  ansible.builtin.template:
    backup: true
    src: ntp.conf.j2
    dest: /etc/ntp.conf
    mode: "644"

- name: ensure ntp is running
  ansible.builtin.service:
    name: ntp
    enabled: true
    state: started
