---

- name: debian 10 apt repo sources list
  when:
    - not offline_mode | d(false)
    - ansible_distribution == 'Debian'
    - ansible_distribution_major_version == '10'
  notify: update cache
  ansible.builtin.copy:
    dest: /etc/apt/sources.list
    mode: '644'
    content: |
      deb {{ repos_prefix }}{{ repos_deb }}/debian {{ repos_release }} main contrib non-free
      deb {{ repos_prefix }}{{ repos_deb }}/debian {{ repos_release }}-updates main contrib non-free
      deb {{ repos_prefix }}{{ repos_deb_sec }}/debian-security {{ repos_release }}/updates main contrib non-free

- name: debian 11 apt repo sources list
  when:
    - not offline_mode | d(false)
    - ansible_distribution == 'Debian'
    - ansible_distribution_major_version == '11'
  notify: update cache
  ansible.builtin.copy:
    dest: /etc/apt/sources.list
    mode: '644'
    content: |
      deb {{ repos_prefix }}{{ repos_deb }}/debian {{ repos_release }} main contrib non-free
      deb {{ repos_prefix }}{{ repos_deb }}/debian {{ repos_release }}-updates main contrib non-free
      deb {{ repos_prefix }}{{ repos_deb_sec }}/debian-security {{ repos_release }}-security main contrib non-free

- name: add ubicast apt repo key
  when: not offline_mode | d(false)
  ansible.builtin.apt_key:
    url: https://{{ repos_skyreach_host }}/media/public.gpg

- name: add ubicast apt repo
  when:
    - not offline_mode | d(false)
    - repos_skyreach_token | d(false)
    - ansible_distribution == 'Debian'
    - ansible_distribution_major_version == '10'
  ansible.builtin.apt_repository:
    repo: deb https://{{ repos_skyreach_host }} packaging/apt/{{ repos_skyreach_token }}/
    filename: ubicast
    update_cache: true

- name: add ubicast apt repo
  when:
    - not offline_mode | d(false)
    - repos_skyreach_token | d(false)
    - ansible_distribution == 'Debian'
    - ansible_distribution_major_version == '11'
  ansible.builtin.apt_repository:
    repo: deb https://{{ repos_skyreach_host }} packaging/apt/{{ repos_skyreach_token }}/bullseye/
    filename: ubicast
    update_cache: true

- name: add ubicast security apt repo
  when:
    - not offline_mode | d(false)
    - ansible_distribution == 'Debian'
    - ansible_distribution_major_version == '10'
  ansible.builtin.apt_repository:
    repo: deb https://{{ repos_skyreach_host }} packaging/apt/ubicast-security-updates/
    filename: ubicast-secu
    update_cache: true

- name: add ubicast security apt repo
  when:
    - not offline_mode | d(false)
    - ansible_distribution == 'Debian'
    - ansible_distribution_major_version == '11'
  ansible.builtin.apt_repository:
    repo: deb https://{{ repos_skyreach_host }} packaging/apt/ubicast-security-updates/bullseye/
    filename: ubicast-secu
    update_cache: true

...
