---
- name: restart lxc
  ansible.builtin.systemd:
    name: lxc
    state: restarted
  changed_when: true
  notify: restart lxc-net

- name: restart lxc-net
  ansible.builtin.systemd:
    name: lxc-net
    state: restarted
