---

- name: "Set default locale"
  ansible.builtin.template:
    src: locale.j2
    dest: /etc/default/locale
    mode: "644"

# Manages locales by editing /etc/locale.gen and invoking locale-gen
- name: "Generate current locales"
  community.general.locale_gen:
    name: "{{ init_locale }}"

...
