---

- name: create databases
  become: true
  become_user: postgres
  loop: "{{ database_databases }}"
  community.general.postgresql_db:
    name: "{{ item.name }}"
    owner: "{{ item.owner | d(omit) }}"

...
