---

# front:
#   IPv4 address used to join the celerity server
# task_management_client:
#   IP or domain on which the celerity server service can be joined
# task_management_server:
#   IP or domain on which the celerity server service can be joined
celerity_server_domain: "{{ hostvars[groups['task_management_server'][0]]['ansible_default_ipv4']['address'] }}"

# front:
#   Key used to encrypt communications to and from celerity server
# task_management_client:
#   Secret key shared between celerity server and workers for communications (should be the same everywhere for communication)
# task_management_server:
#   Secret key shared between celerity server and workers for communications (should be the same everywhere for communication)
celerity_signing_key: "my-signing-key"

# cache:
#   URL of the Nudgis Live cluster
# live:
#   Domain name of the live cluster (only if distinct live server(s) from MediaServer and live_ha variable is set to True)
live_domain: "nudgis.ubica.st"

# front:
#   Defines the default deployed Nudgis portal linked mirismanager domain (correspond to the URL of the mirismanager portal when adding the HTTP(S) prefix)
# manager:
#   Defines the default domain for the Nudgis Manager
manager_domain: "manager.ubica.st"

# front:
#   Defines the default deployed Nudgis portal master API key
# task_management_client:
#   Nudgis API key, used to communicate with the nudgis portal
# task_management_server:
#   Nudgis API key, used to communicate with the nudgis portal
nudgis_front_api_key: "XXXXX-XXXXX-XXXXX-XXXXX-XXXXX"

# cache:
#   URL of Nudgis Front cluster
# front:
#   Defines the default deployed Nudgis portal domain (will be the URL of the portal when adding the HTTP(S) prefix)
# task_management_client:
#   URL of the default Nudgis "msuser" portal used to populate the /etc/celerity/config.py file
# task_management_server:
#   Defines the default deployed Nudgis portal domain (will be the URL of the portal when adding the HTTP(S) prefix)
nudgis_front_domain: "nudgis.ubica.st"

# front:
#   In offline mode, UbiCast employees web accesses (for maintenance) are not deployed
# manager:
#   In offline mode, UbiCast employees web accesses (for maintenance) are not deployed
# monitor_server:
#   In offline mode, UbiCast employees web accesses (for maintenance) are not deployed
# ssh:
#   Do not configure any ubicast ssh public key
#offline_mode: false

# monitor_client:
#   Short name of the customer, with no spaces. This name is used in munin to group the graphs under the same name.
# monitor_server:
#   Short name of the customer, with no spaces. This name is used in munin to group the graphs under the same name.
ubicast_customer_name: "UbiCast-Std"

...