---

# Define the default action to do when a ban occurs ("action_mwl" to send whois and logs via email or "action_" for default)
#fail2ban_action: "action_mwl"

# Duration of bans
#fail2ban_bantime: "10m"

# Email sender of the fail2ban reports
#fail2ban_email_from: "root@localhost"

# Email reciepient of the fail2ban reports
#fail2ban_email_to: "noreply@example.com"

# IP addresses exceptions (no monitored by fail2ban)
#fail2ban_ignoreip: "127.0.0.1/8 ::1"

# Number of acceptable failures before banning an IP
#fail2ban_maxretry: "5"

...