---

# Defines the default domain for monitor
monitor_domain: "monitor.ubica.st"

# Password for the webmonitor admin user
monitor_user_admin_password: "my-password"

# List of munin_nodes with their names and IP (each element of the list is a dictionary with a "name" and a "ip" key)
#munin_nodes: []

...