---

# Defines the default domain for monitor
monitor_domain: "monitor.ubica.st"

# Password for the webmonitor ubicast user
monitor_user_ubicast_password: "my-password"

# Password for the webmonitor admin user
monitor_user_admin_password: "my-password"

...
