---

# Debian distribution short name (example: "bullseye")
#repos_release: "{{ ansible_distribution_release }}"

# Value for the system locale
init_locale: "en_GB.UTF-8"

# Timezone to set on the servers (`timedatectl list-timezones` for the complete list)
#init_timezone: "Europe/Paris"

# Domain to use for the Debian repositories
#repos_debian_packages_domain: "deb.debian.org"

# Domain to use for the Debian security repositories
#repos_debian_security_packages_domain: "security.debian.org"

...
