---

- name: "Gather hostname"
  ansible.builtin.setup:
    filter: ansible_facts['hostname']

- name: "Postfix generic"
  notify: "Postmap generic"
  ansible.builtin.template:
    backup: true
    src: generic.j2
    dest: /etc/postfix/generic
    mode: "644"

...
