---

nudgis_front_domain: "nudgis.example.com"
nudgis_front_email_from: "noreply@{{ nudgis_front_domain }}"
nudgis_front_system_user: "msuser"
manager_domain: "manager.example.com"
nudgis_front_api_key: "XXXXX-XXXXX-XXXXX-XXXXX-XXXXX"
nudgis_front_user_ubicast_password: "changeit"
nudgis_front_user_admin_password: "changeit"

nudgis_front_database_domain: "database.nudgis.example.com"
nudgis_front_database_port: "5432"
nudgis_front_database_password: "changeit"
nudgis_front_instances_dir: "/data"

celerity_signing_key: "changeit"
celerity_server_domain: "celerity.example.com"

real_ip_from: "" # default for OVH LB is 10.108.0.0/14
...
