---

- name: packages
  apt:
    force_apt_get: true
    install_recommends: false
    name: "{{ ferm_packages }}"
  register: apt_status
  retries: 60
  until: apt_status is success or ('Failed to lock apt for exclusive operation' not in apt_status.msg and '/var/lib/dpkg/lock' not in apt_status.msg)

- name: configuration
  notify: restart ferm
  template:
    src: ferm.conf.j2
    dest: /etc/ferm/ferm.conf
    backup: true

- name: service
  systemd:
    name: ferm
    enabled: true
    masked: false
    state: started

...
