# Configuration file for installation and post installation scripts.
# IMPORTANT:
# This file must be readable ONLY by root to avoid revealing passwords.
# After any change, please reinstall the package to trigger the reconfiguration.

[conf]
# Domain to use for the application.
# DOMAIN = monitor.example.com

# Superuser account (ubicast) password.
# SUPERUSER_PWD = changeit

# Admin account (admin) password.
# The account will not be able to log in if no password is set.
# ADMIN_PWD =

