---

- name: "Restart postgresql"
  ansible.builtin.systemd:
    name: postgresql@{{ database_version }}-{{ database_cluster }}
    state: restarted

- ansible.builtin.import_tasks: ../../shared/handlers/nftables.yml

...
