---

# Packages required for the group
init_packages:
  - openssh-client
  - ca-certificates
  - apt-utils
  - gnupg
  - sudo

# Packages required for the group
sysconfig_packages:
  - openssh-server
  - bash-completion
  - unattended-upgrades
  - man
  - vim
  - ifupdown
  - lm-sensors
  - smartmontools
  - curl
  - host
  - htop

# Debian distribution short name (example: "bullseye")
repos_release: "{{ ansible_distribution_release }}"

# Packages required for the group
locale_packages:
  - locales
  - tzdata

# Packages required for the group
sysconfig_repos_packages:
  - python3-debian

# Repository keyring path
sysconfig_repos_keyrings_dir: "/usr/local/share/keyrings"

...
