---
- name: install bench-worker packages
  ansible.builtin.apt:
    force_apt_get: true
    install_recommends: false
    update_cache: true
    name: "{{ bench_worker_packages }}"
    state: latest
  register: apt_status
  retries: 60
  until: apt_status is success or ('Failed to lock apt for exclusive operation' not in apt_status.msg and '/var/lib/dpkg/lock' not in apt_status.msg)

- name: ensure configuration directory exists
  ansible.builtin.file:
    path: /etc/mediaserver
    state: directory
    mode: "755"

- name: benchmark configuration settings
  ansible.builtin.copy:
    dest: /etc/mediaserver/bench-conf.json
    content: |
      {
      "LOCUST_HOST":"{{ bench_server }}",
      "MS_HOST":"{{ bench_host }}",
      "MS_USERNAME":"{{ bench_user }}",
      "MS_PASSWORD":"{{ bench_password }}",
      "MEDIA_OID":"{{ bench_oid }}",
      "DL_STREAMS":{{ bench_dl_streams }},
      "TIME_STATS":{{ bench_time_stat }}
      }
    mode: "644"

- name: reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: restart bench-worker
  ansible.builtin.systemd:
    name: bench-worker
    state: restarted
