---

- name: "Ensure postgres account have a ssh keypair"
  ansible.builtin.user:
    name: postgres
    generate_ssh_key: true
    ssh_key_type: ed25519
    ssh_key_file: ~postgres/.ssh/id_ed25519

- name: "Fetch postgres ssh public key"
  register: repmgr_postgres_ssh_pubkey
  ansible.builtin.slurp:
    path: ~postgres/.ssh/id_ed25519.pub

- name: "Register postgres ssh public key as an ansible fact"
  ansible.builtin.set_fact:
    pubkey: "{{ repmgr_postgres_ssh_pubkey['content'] | b64decode }}"

- name: "Share postgres ssh public key between cluster members"
  loop: "{{ groups['postgres'] }}"
  ansible.posix.authorized_key:
    user: postgres
    key: "{{ hostvars[item]['pubkey'] }}"

- name: "Postgres ssh client configuration"
  ansible.builtin.copy:
    dest: ~postgres/.ssh/config
    owner: postgres
    group: postgres
    mode: "640"
    content: |
      IdentityFile ~/.ssh/id_ed25519
      StrictHostKeyChecking no
      UserKnownHostsFile /dev/null

...
