---

# customer name
customer_short_name: customer

# enable letsencrypt certificate
letsencrypt_enabled: false

# update conf.sh
conf_update: false

# repmgr configuration
repmgr_password: my top secret repmgr default password
repmgr_primary_node: "{{ hostvars['pg1']['ansible_default_ipv4']['address'] }}"

# ha proxy configuration
hap_config_listen:
  - name: pgsql-primary
    content: |2
      bind localhost:54321
      default-server inter 2s fall 3 rise 2 on-marked-down shutdown-sessions
      option tcp-check
      tcp-check expect string primary
      maxconn 500
      server pg1 192.168.122.1:5432 maxconn 500 check port 8543
      server pg2 192.168.122.2:5432 maxconn 500 check port 8543 backup

...
