#!/usr/bin/env ansible-playbook
---

- name: "REHACHECK STATUS"
  hosts: postgres_primary:postgres_standby:postgres_fenced
  tasks:
    - name: "Get cluster state"
      ansible.builtin.command: rephacheck
      register: rephacheck
      changed_when: false

    - name: "Show status for each node"
      ansible.builtin.debug:
        msg: Current node {{ ansible_hostname }} status {{ rephacheck['stdout'] }}
      when: rephacheck['stdout'] | length > 0

...
