---

- name: "Update logrotate config"
  ansible.builtin.copy:
    src: logrotate-postgresql
    dest: /etc/logrotate.d/postgresql-common
    owner: root
    group: root
    backup: false
    mode: "644"

...
