---
- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: restart postgresql
  ansible.builtin.systemd:
    name: postgresql@{{ repmgr_pg_version }}-{{ repmgr_pg_cluster }}
    state: restarted

- name: restart repmgrd
  ansible.builtin.systemd:
    name: repmgrd
    state: restarted

- name: restart rephacheck
  ansible.builtin.systemd:
    name: rephacheck.socket
    state: restarted
