# Configuration file for installation and post installation scripts.
# IMPORTANT:
# This file must be readable ONLY by root to avoid revealing passwords.

[conf]
# Database host.
# Can be a hostname or an IP.
# This setting is ignored if a value is already set in the local settings file.
# DB_HOST = 127.0.0.1

# Database port.
# This setting is ignored if a value is already set in the local settings file.
# DB_PORT = 5432

# Database postgres account password.
# DB_ROOT_PWD =

# Domain to use for the application.
# This setting is used only if the Nginx vhost is using the default domain "skyreach".
# DOMAIN = skyreach.example.com

# Administrator account ("admin") password.
# This setting is used only for the initial data creation.
# ADMIN_PWD =

# API key of this skyreach site.
# This key is used to be able to synchronize packages and systems with the upstream skyreach.
# This setting is ignored if a value is already set in the local settings file.
# API_KEY =

# Secret key of this skyreach site.
# This key is used to be able to synchronize packages and systems with the upstream skyreach.
# This setting is ignored if a value is already set in the local settings file.
# SECRET_KEY =
