---

# Packages required for the group. python3-systemd is used to read systemd journal
fail2ban_packages:
  - fail2ban
  - python3-systemd

# IP addresses exceptions (no monitored by fail2ban)
fail2ban_ignoreip: "127.0.0.1/8 ::1"

# Number of acceptable failures before banning an IP
fail2ban_maxretry: "5"

# Duration of bans
fail2ban_bantime: "10m"

# Define the default action to do when a ban occurs ("action_mwl" to send whois and logs via email or "action_" for default)
fail2ban_action: "action_"

...
