---

- name: install kibana package
  ansible.builtin.apt:
    force_apt_get: true
    install_recommends: false
    name: kibana
    state: present
  register: apt_status
  retries: 60
  until: apt_status is success or ('Failed to lock apt for exclusive operation' not in apt_status.msg and '/var/lib/dpkg/lock' not in apt_status.msg)

- name: deploy kibana configuration
  ansible.builtin.template:
    src: kibana.yml.j2
    dest: /etc/kibana/kibana.yml
    mode: "644"
  notify: restart kibana

- name: install apm-server package
  ansible.builtin.apt:
    force_apt_get: true
    install_recommends: false
    name: apm-server
    state: present
  register: apt_status
  retries: 60
  until: apt_status is success or ('Failed to lock apt for exclusive operation' not in apt_status.msg and '/var/lib/dpkg/lock' not in apt_status.msg)

- name: deploy apm-server configuration
  ansible.builtin.template:
    src: apm-server.yml.j2
    dest: /etc/apm-server/apm-server.yml
    mode: "644"
  notify: restart apm-server

...
