---
postfix_mailname: "domain.example.com"
postfix_email_from: "noreply@{{ postfix_mailname }}"
postfix_relay_host: ""
postfix_relay_user: ""
postfix_relay_pass: ""
postfix_admin: "admin@example.com"
...
