---

- name: "Configure (or update) msconf with celerity server info"
  ansible.builtin.lineinfile:
    path: /var/lib/ubicast-mediaserver/common/msconf.py
    regexp: '^#?\s*{{ item.name }}\s*=.*$'
    line: "{{ item.name }} = '{{ item.value }}'"
    create: true
    owner: root
    group: root
    # 644 as all the instances must reach this file
    # The instances cannot be in a common group as of now
    # See https://redmine.ubicast.net/issues/33046
    mode: "0644"
  loop:
    - { name: 'CELERITY_SERVER_URL', value: 'https://{{ celerity_server_domain }}:6200' }
    - { name: 'CELERITY_SIGNING_KEY', value: '{{ celerity_signing_key }}' }

...
