---

# Tasks executed in HA mode only
# Verify mediaserver files are shared accross all servers

- name: "Create shared witness file"
  ansible.builtin.copy:
    content: "test"
    dest: /var/lib/ubicast-mediaserver/shared-witness
  delegate_to: "{{ groups['front'][0] }}"
  run_once: true
  changed_when: false

- name: "Check shared file between each frontend"
  ansible.builtin.stat:
    path: /var/lib/ubicast-mediaserver/shared-witness
  register: shared_file
  failed_when: not shared_file.stat.exists
  changed_when: false

- name: "Ensure shared file exists on all frontends"
  ansible.builtin.assert:
    that:
      - shared_file.stat.exists
    fail_msg: "Shared witness file missing: {{ inventory_hostname }} (shared storage issue?)"

- name: "Cleanup shared witness file"
  ansible.builtin.file:
    path: /var/lib/ubicast-mediaserver/shared-witness
    state: absent
  delegate_to: "{{ groups['front'][0] }}"
  run_once: true
  changed_when: false

...
