---

- name: "Fetch ssh public key"
  register: root_ssh_pubkey
  ansible.builtin.slurp:
    path: /root/.ssh/id_ed25519.pub
  tags: always

- name: "Register ssh public key as an ansible fact"
  ansible.builtin.set_fact:
    pubkey: "{{ root_ssh_pubkey['content'] | b64decode }}"
  tags: always

- name: "Share ssh public key between cluster members"
  loop: "{{ groups['front'] }}"
  ansible.posix.authorized_key:
    user: root
    key: "{{ hostvars[item]['pubkey'] }}"
  tags: always

- name: "Synchronize configuration between servers"  # noqa: command-instead-of-module
  # Cannot use the ansible synchronization module, cause there is no way to set a destination IP intead of the destination ansible hostname
  delegate_to: "{{ groups['front'][0] }}"
  when:
    - inventory_hostname != groups['front'][0]
  loop:
    - /etc/mediaserver
    - /etc/nginx
    - /etc/sysusers.d
    - /var/www
  ansible.builtin.command: |
    rsync \
      -avh \
      --delete \
      -e "ssh -o StrictHostKeyChecking=no" \
      "{{ item }}/" \
      "root@{{ ansible_facts['default_ipv4']['address'] }}:{{ item }}/"
  notify:
    - "Restart systemd-sysusers"
    - "Restart nginx"
    - "Restart mediaserver"
  changed_when: false
  tags: fronts-synchronize

...
