---

- name: "Remove postfix conflicting packages"
  ansible.builtin.import_role:
    name: "nudgis/shared"
    tasks_from: "apt_install.yml"
  vars:
    apt_packages:
      - "exim4"
      - "exim4-base"
      - "exim4-config"
      - "exim4-daemon-light"
    apt_packages_state: "absent"
    apt_packages_purge: true

- name: "Install postfix"
  ansible.builtin.import_role:
    name: "nudgis/shared"
    tasks_from: "apt_install.yml"
  vars:
    apt_packages: "{{ postfix_packages }}"

...
