---

- name: "Create fail2ban path-overrides"
  notify: "Restart fail2ban"
  ansible.builtin.copy:
    dest: /etc/fail2ban/paths-overrides.local
    mode: "644"
    force: false
    content: |
      [DEFAULT]

- name: "Configure sshd jail backend"
  notify: "Restart fail2ban"
  ansible.builtin.lineinfile:
    path: /etc/fail2ban/paths-overrides.local
    regexp: '^sshd_backend'
    insertafter: '[DEFAULT]'
    line: 'sshd_backend = systemd'

- name: "Service"
  ansible.builtin.systemd:
    name: fail2ban
    enabled: true
    state: started

...
