---

# Packages required for the group. python3-psycopg2 is used by ansible
database_packages:
  - acl
  - postgresql
  - python3-psycopg2

# PostgreSQL database version
database_version: "15"

# PostgreSQL database cluster name
database_cluster: "main"

# PostgreSQL database cluster path
database_conf_dir: "/etc/postgresql/{{ database_version }}/{{ database_cluster }}"

# PostgreSQL user/host connection file
database_host_authentification:
  - method: peer
    type: local
  - address: 127.0.0.1/32
    type: hostssl
  - address: ::1/128
    type: hostssl
  - database: replication
    method: peer
    type: local
  - address: 127.0.0.1/32
    database: replication
    type: hostssl
  - address: ::1/128
    database: replication
    type: hostssl

# PostgreSQL configuration key/values
database_conf:
  - content: ''
    name: main

# Dictionnary of extra databases to deploy (with `name` and `owner` keys)
database_databases: []

# Dictionnary of extra PostgreSQL users to deploy (with `name`, `password`, `db`, `priv` and `roles` keys)
database_users: []

# Group firewall rules filename, see roles/shared/files/nftables/
firewall_rules_files:
  - postgres

...
