---
- name: proxy
  when:
    - proxy_http | d()
    - proxy_https | d()
  ansible.builtin.include_role:
    name: proxy

- name: install requirements
  ansible.builtin.apt:
    force_apt_get: true
    install_recommends: false
    name: "{{ conf_req_packages }}"
  register: apt_status
  retries: 60
  until: apt_status is success or ('Failed to lock apt for exclusive operation' not in apt_status.msg and '/var/lib/dpkg/lock' not in apt_status.msg)

- name: generate root ssh key pair
  register: conf_root
  ansible.builtin.user:
    name: root
    generate_ssh_key: true
    ssh_key_type: ed25519
    ssh_key_file: .ssh/id_ed25519
...
