---

- name: "Stats Webmonitor main configuration file"
  ansible.builtin.stat:
    path: "/etc/webmonitor/install.ini"
  register: monitor_config

- name: "Populate Webmonitor base configuration with example values"
  when:
    - monitor_config['stat'] is defined
    - not monitor_config['stat']['exists']
  ansible.builtin.copy:
    src: "/etc/webmonitor/install.example.ini"
    dest: "/etc/webmonitor/install.ini"
    mode: "preserve"
    remote_src: true

- name: 'Disable default cron email'
  ansible.builtin.lineinfile:
    path: /etc/cron.d/munin-node
    regexp: '^MAILTO=root$'
    line: '#MAILTO=root'
    state: present
    backrefs: true

- ansible.builtin.import_role:
    name: "nudgis/shared"
    tasks_from: "firewall_rules_files.yml"
  vars:
    firewall_rules_files: "{{ monitor_server_firewall_rules_files }}"

...
