---

- name: create mailer script
  when: mvt_mailer_enabled
  ansible.builtin.template:
    src: systemd-mailer-script.j2
    dest: "{{ mvt_mailer_script_path }}"
    mode: "0755"

- name: create mailer service
  when: mvt_mailer_enabled
  notify: systemd daemon reload
  ansible.builtin.template:
    src: systemd-mailer-service.j2
    dest: "{{ mvt_mailer_service_path }}"
    mode: "0644"

...
