---

- name: Configure mailer
  when: vault_email_enabled
  block:
    - name: create mailer script
      ansible.builtin.template:
        src: systemd-mailer-script.j2
        dest: "{{ vault_email_script_path }}"
        mode: "0755"

    - name: create mailer service
      notify: systemd daemon reload
      ansible.builtin.template:
        src: systemd-mailer-service.j2
        dest: "{{ vault_email_service_path }}"
        mode: "0644"

...
