---

- name: install packages
  ansible.builtin.package:
    force_apt_get: true
    install_recommends: false
    name: "{{ vault_packages }}"
    state: present

- name: generate ssh keys pair
  ansible.builtin.user:
    name: root
    generate_ssh_key: true
    ssh_key_type: ed25519
    ssh_key_file: .ssh/id_ed25519

# MAILER
- name: MAILER
  ansible.builtin.include_tasks: mailer.yml

- ansible.builtin.meta: flush_handlers # noqa name[missing]

...
