---

# Short name of the customer, with no spaces. This name is used in munin to group the graphs under the same name.
ubicast_customer_name: "example"

# IP of the munin server to authorize in munin_node
munin_server_ip: ""

...
