---

- name: "Trigger dpkg-reconfigure tzdata"
  # https://unix.stackexchange.com/questions/451709/timedatectl-set-timezone-doesnt-update-etc-timezone
  # timedatectl do not update the /etc/timezone file...
  ansible.builtin.command:
    cmd: dpkg-reconfigure --frontend noninteractive tzdata
  changed_when: false

...
