# Configuration file for installation and post installation scripts.
# IMPORTANT:
# This file must be readable ONLY by root to avoid revealing passwords.

[conf]
# Database host.
# Can be a hostname or an IP.
# DB_HOST = 127.0.0.1

# Database port.
# DB_PORT = 5432

# Database superuser account name.
# This account is used during deployments and upgrades.
# DB_ROOT_USER =

# Database superuser account password.
# This account is used during deployments and upgrades.
# DB_ROOT_PWD =

# Maximum number of database dump files to keep when running the dump action.
# DB_DUMP_MAX_FILES = 31

# Enable the creation of a database dump before running an update.
# The pre update database dump will be skipped if it has already been made within the last hour.
# Possible values: `yes` (default) or `no`.
# DB_DUMP_PRE_UPDATE = yes

# Directories pattern for new instance creation.
# Can contain a glob part, for example: `/data/nas*`.
# DATA_NEW_DIRS = /data

# Directory for the `mscontroller` script lock files.
# Several files are used as lock by the script, depending on which actions are running.
# When using multiple frontend servers, this directory must be shared by all servers (NAS).
# Example: `/data`. If no value is set, `/var/lock` will be used.
# MSCONTROLLER_LOCKS_DIR =

