---

# Defines the default deployed Nudgis portal short name (and linked unix user) **shared with celerity and mediaworker roles**
nudgis_front_system_user: "ubicast-mediaserver-portal"

# Directory to store the Nudgis portals data (configuration, media, etc.)
nudgis_front_instances_dir: "/data"

# Directory to store the Nudgis lock files. This directory should be shared between the Nudgis Fronts in HA cases.
nudgis_front_lock_dir: "/var/lib/ubicast-mediaserver/locks"

# Packages required for the group. rsync is used for HA only (copy of instance data)
nudgis_front_packages:
  - postgresql-client
  - cron
  - memcached
  - nginx
  - postfix
  - ubicast-mediaserver
  - rsync

# Packages to install only when the system is not in offline mode
nudgis_front_online_packages:
  - ubicast-web-access

# Group firewall rules filename, see roles/shared/files/nftables/
nudgis_firewall_rules_files:
  - http

...
