---

- name: "Create netcapture config"
  ansible.builtin.template:
    src: netcapture.json.j2
    dest: /etc/miris/netcapture.json
    mode: u=rw,g=r,o=r

- name: "Netcapture config dir"
  ansible.builtin.file:
    path: "{{ netcapture_conf_folder }}"
    group: video
    mode: u=rwX,g=rwX,o=rx
    state: directory

- name: "Netcapture media dir"
  ansible.builtin.file:
    path: "{{ netcapture_media_folder }}"
    group: video
    mode: u=rwX,g=rwX,o=rx
    state: directory

- name: "Netcapture package dir"
  ansible.builtin.file:
    path: "{{ netcapture_pkg_folder }}"
    mode: u=rwX,g=rwX,o=rx
    state: directory

...
