---

- name: BASE CONFIGURE POSTGRESQL LOGROTATE
  ansible.builtin.include_tasks: "base/logrotate.yml"

- import_tasks: ../../shared/tasks/firewall_rules_files.yml  # noqa: name[missing]

- name: flush handlers
  ansible.builtin.meta: flush_handlers

...
