---

# Configurartions files must stay here even without variables
# This role can be called from postgres-ha (with configure tag) with custom variables

- name: CONFIGURE POSTGRESQL CUSTOM SETTINGS
  ansible.builtin.include_tasks: "configure/custom-settings.yml"

- name: CONFIGURE POSTGRESQL EXTERNAL AUTHENTICATIONS
  ansible.builtin.include_tasks: "configure/authentication.yml"

- name: CONFIGURE POSTGRESQL INTERNAL USERS
  ansible.builtin.include_tasks: "configure/users.yml"
  when:
    - database_password is defined

- name: CREATE POSTGRESQL DATABASES
  ansible.builtin.include_tasks: "configure/databases.yml"

# Flush to restart postgresql in time for HA deployment
- name: Flush handlers
  meta: flush_handlers

...
