---

- name: CONFIGURE UBICAST-TESTER
  ansible.builtin.include_tasks: "configure/letsencrypt-configure.yml"
  when:
    - letsencrypt_domains is defined
    - letsencrypt_email is defined
    - letsencrypt_webroot is defined

...
