#!/usr/bin/env ansible-playbook
---
- name: MEDIASERVER
  hosts: mediaserver
  tags: mediaserver
  roles:
    - mediaserver
  post_tasks:
    - name: deploy letsencrypt certificate
      when: letsencrypt_enabled | d(false)
      ansible.builtin.include_role:
        name: letsencrypt
    - name: configure proxy
      when: proxy_apply | d(false)
      ansible.builtin.include_role:
        name: proxy
