#!/usr/bin/env ansible-playbook
---

- name: MEDIACACHE
  hosts: mediacache
  tags: mediacache
  roles:
    - mediacache
  post_tasks:
    - name: deploy letsencrypt certificate
      when: letsencrypt_enabled | d(false)
      include_role:
        name: letsencrypt
    - name: configure network
      when: network_apply | d(false)
      include_role:
        name: network
    - name: configure proxy
      when: proxy_apply | d(false)
      include_role:
        name: proxy

...
