#!/usr/bin/env ansible-playbook
---

- name: MEDIAWORKER
  hosts: mediaworker
  tags: mediaworker
  roles:
    - mediaworker
  post_tasks:
    - name: configure network
      when: network_apply | d(false)
      ansible.builtin.include_role:
        name: network
    - name: configure proxy
      when: proxy_apply | d(false)
      ansible.builtin.include_role:
        name: proxy

...
