#!/usr/bin/env ansible-playbook
---

- name: MIRIS MANAGER
  hosts: mirismanager
  tags: mirismanager
  roles:
    - mirismanager
  post_tasks:
    - name: deploy letsencrypt certificate
      when: letsencrypt_enabled | d(false)
      ansible.builtin.include_role:
        name: letsencrypt
    - name: configure proxy
      when: proxy_apply | d(false)
      ansible.builtin.include_role:
        name: proxy

...
