#!/usr/bin/env ansible-playbook
---

- name: NETCAPTURE
  hosts: netcapture
  tags: netcapture
  roles:
    - netcapture
  post_tasks:
    - name: configure network
      when: network_apply | d(false)
      ansible.builtin.include_role:
        name: network
    - name: configure proxy
      when: proxy_apply | d(false)
      ansible.builtin.include_role:
        name: proxy

...
