#!/usr/bin/env ansible-playbook
---

- name: POSTGRESQL
  hosts: postgres
  tags: postgres
  roles:
    - postgres
  post_tasks:
    - name: configure network
      when: network_apply | d(false)
      include_role:
        name: network
    - name: configure proxy
      when: proxy_apply | d(false)
      include_role:
        name: proxy

...
