#!/usr/bin/env ansible-playbook
---

- name: PYTHON
  hosts: all
  gather_facts: false
  tasks:
    - name: ensure python3 is installed
      register: python_install
      changed_when: "'es_pyinstall' in python_install.stdout_lines"
      ansible.builtin.raw: command -v python3 || echo es_pyinstall && apt update && apt install -y python3-minimal python3-apt iproute2

# Should be in a installation role (see #39283)
- name: UPDATE PACKAGES
  hosts: base
  gather_facts: false
  tags: install
  tasks:
    - name: Update apt cache
      apt:
        update_cache: true
        cache_valid_time: 86400
      changed_when: false

- import_playbook: base.yml

- import_playbook: firewall.yml

- import_playbook: "{{ 'postgres-ha' if groups['postgres']|d('') | length > 1 else 'postgres' }}.yml"

- import_playbook: mirismanager.yml

- import_playbook: celerity.yml

- import_playbook: mediaworker.yml

- import_playbook: mediaserver.yml

- import_playbook: live/live.yml

- import_playbook: mediacache/mediacache.yml

- import_playbook: mediavault/deploy.yml

- import_playbook: mediaimport.yml

- import_playbook: netcapture/netcapture.yml

- import_playbook: monitor/all.yml

- import_playbook: tester.yml

...
