#!/usr/bin/env ansible-playbook
---
- name: MEDIAVAULT
  hosts: mediavault
  tags: mediavault
  roles:
    - mediavault
  post_tasks:
    - name: configure network
      when: network_apply | d(false)
      ansible.builtin.include_role:
        name: network
    - name: configure proxy
      when: proxy_apply | d(false)
      ansible.builtin.include_role:
        name: proxy
