#!/usr/bin/env ansible-playbook
---

- name: MEDIAVAULT
  hosts: mediavault
  tags: mediavault
  pre_tasks:
    - name: check running in a docker container
      register: check_if_docker
      stat:
        path: /.dockerenv
    - name: set docker flag variable
      set_fact:
        in_docker: "{{ check_if_docker.stat.exists | d(false) }}"
  roles:
    - mediavault
  post_tasks:
    - name: configure network
      when: network_apply | d(false)
      include_role:
        name: network
    - name: configure proxy
      when: proxy_apply | d(false)
      include_role:
        name: proxy

...
