---

# Packages required for the group. Comes from ubicast-skyreach-runtime packages
dependencies_packages:
  - cron
  - nginx
  - postfix
  - postgresql

# Packages required for the group
manager_packages:
  - ubicast-skyreach

# Group firewall rules filename, see roles/shared/files/nftables/
firewall_rules_files:
  - http

...
