# Configuration file for installation and post installation scripts.
# IMPORTANT:
# This file must be readable ONLY by root to avoid revealing passwords.

[conf]
# Database host.
# Can be a hostname or an IP.
# DB_HOST = 127.0.0.1

# Database port.
# DB_PORT = 5432

# Database postgres account password.
# DB_ROOT_PWD =

# Domain to use for the application.
# DOMAIN = skyreach.example.com

# Superuser account (ubicast) password.
# SUPERUSER_PWD = changeit

# Admin account password.
# ADMIN_PWD =

# API key of this skyreach site.
# This key is used to be able to synchronize packages and systems with the upstream skyreach.
# API_KEY =

# Secret key of this skyreach site.
# This key is used to be able to synchronize packages and systems with the upstream skyreach.
# SECRET_KEY =

