---

- name: "CONFIGURE SUDOERS"
  ansible.builtin.include_tasks: "base/sudoers.yml"

- name: "SETUP USERS"
  ansible.builtin.include_tasks: "base/setup_user.yml"
  loop:
    - admin
    - ubicast
  vars:
    user: "{{ item }}"

- name: "CONFIGURE DOTFILES"
  ansible.builtin.include_tasks: "base/dotfiles.yml"
  loop:
    - root
    - admin
    - ubicast
  vars:
    user: "{{ item }}"

...
