---

- name: "CONFIGURE SUDOERS"
  ansible.builtin.include_tasks: "base/sudoers.yml"

- name: "SETUP USERS"
  ansible.builtin.include_tasks: "base/setup_user.yml"
  loop:
    - { name: "ubicast", id: 1000 }
    - { name: "admin", id: 1001 }
  vars:
    user_name: "{{ item.name }}"
    user_id: "{{ item.id }}"

- name: "CONFIGURE DOTFILES"
  ansible.builtin.include_tasks: "base/dotfiles.yml"
  loop:
    - root
    - admin
    - ubicast
  vars:
    user: "{{ item }}"

...
