---
- name: install ubicast msmonitor
  ansible.builtin.apt:
    force_apt_get: true
    install_recommends: false
    state: latest
    name:
      - ubicast-webmonitor
      - ubicast-webmonitor-runtime
  register: apt_status
  retries: 60
  until: apt_status is success or ('Failed to lock apt for exclusive operation' not in apt_status.msg and '/var/lib/dpkg/lock' not in apt_status.msg)

- name: ensure msmonitor is running
  ansible.builtin.service:
    name: webmonitor
    enabled: true
    state: started

# FIREWALL

- name: firewall
  when: monitor_firewall_enabled
  vars:
    ferm_rules_filename: "{{ monitor_ferm_rules_filename }}"
    ferm_input_rules: "{{ monitor_ferm_input_rules }}"
    ferm_output_rules: "{{ monitor_ferm_output_rules }}"
    ferm_global_settings: "{{ monitor_ferm_global_settings }}"
  ansible.builtin.include_role:
    name: ferm-configure
