---

- name: "Copy munin_server configuration"
  notify: "Restart munin-server"
  ansible.builtin.template:
    src: munin.conf.j2
    dest: /etc/munin/munin.conf
    mode: "644"

# Force munin (server) restart to avoid default localdomain graph creation after remove
- name: "Flush handlers"
  ansible.builtin.meta: flush_handlers

# Remove default localdomain graph created after installation and before configuration
- name: "Check the existence of the localdomain folder"
  ansible.builtin.stat:
    path: /var/cache/munin/www/localdomain
  register: localdomain_dir

# Command module is used instead of the file (absent) module to allow a recursive deletion
- name: "Remove default localdomain directory and files"
  ansible.builtin.command:
    cmd: /bin/rm -r /var/cache/munin/www/localdomain
    removes: /var/cache/munin/www/localdomain
  when: localdomain_dir.stat.exists

...
