---

# At installation, admin user is created with an empty or random password
# See RM#40081 for details

- name: "Update admin password"
  ansible.builtin.command:
    cmd: >
      ubicast-webmonitor-ctl user update
        --target "username=admin"
        --password "{{ monitor_user_admin_password }}"
    changed_when: false

...
