---

- name: install celerity worker
  ansible.builtin.apt:
    force_apt_get: true
    install_recommends: false
    name: celerity-workers
  register: apt_status
  retries: 60
  until: apt_status is success or ('Failed to lock apt for exclusive operation' not in apt_status.msg and '/var/lib/dpkg/lock' not in apt_status.msg)

- name: config celerity worker
  notify: restart celerity-workers
  ansible.builtin.template:
    src: celerity-config.py.j2
    dest: /etc/celerity/config.py
    mode: '644'

- name: ensure celerity worker is running
  ansible.builtin.service:
    name: celerity-workers
    enabled: true
    state: started

# FIREWALL

- name: firewall
  when: worker_firewall_enabled
  vars:
    ferm_rules_filename: "{{ worker_ferm_rules_filename }}"
    ferm_input_rules: "{{ worker_ferm_input_rules }}"
    ferm_output_rules: "{{ worker_ferm_output_rules }}"
    ferm_global_settings: "{{ worker_ferm_global_settings }}"
  ansible.builtin.include_role:
    name: ferm-configure

- name: flush handlers
  ansible.builtin.meta: flush_handlers

...
