---
# packages to install
ferm_packages:
  - ferm

# default filtering and logging policy for input traffic
ferm_input_policy: DROP
ferm_input_log: false
ferm_input_log_prefix: "{{ ferm_input_policy }} INPUT "

# default filtering and logging for output traffic
ferm_output_policy: ACCEPT
ferm_output_log: false
ferm_output_log_prefix: "{{ ferm_output_policy }} OUTPUT "

# default filtering and logging for forward traffic
ferm_forward_policy: DROP
ferm_forward_log: false
ferm_forward_log_prefix: "{{ ferm_forward_policy }} FORWARD "

# enable anti-lockout rule
ferm_antilockout_enabled: true
