---
# INSTALLATION

- name: install packages
  ansible.builtin.apt:
    force_apt_get: true
    install_recommends: false
    name: "{{ repmgr_packages }}"
  register: apt_status
  retries: 60
  until: apt_status is success or ('Failed to lock apt for exclusive operation' not in apt_status.msg and '/var/lib/dpkg/lock' not in apt_status.msg)

# POSTGRESQL

- name: postgresql
  vars:
    database_host_authentification:
      - type: local
        method: peer
      - type: hostssl
        address: 127.0.0.1/32
      - type: hostssl
        address: ::1/128
      - type: hostssl
        address: 0.0.0.0/0
      - type: hostssl
        address: ::/0
      - type: local
        database: replication
        method: peer
      - type: hostssl
        database: replication
        address: 127.0.0.1/32
      - type: hostssl
        database: replication
        address: ::1/128
      - type: hostssl
        database: replication
        address: 0.0.0.0/0
      - type: hostssl
        database: replication
        address: ::/0
    database_conf:
      - name: main
        content: |
          listen_addresses = '*'
      - name: modules
        content: |
          shared_preload_libraries = 'repmgr'
    database_users:
      - name: "{{ repmgr_user }}"
        password: "{{ repmgr_password }}"
        roles: "{{ repmgr_roles }}"
    database_databases:
      - name: "{{ repmgr_database }}"
        owner: "{{ repmgr_user }}"
  ansible.builtin.include_role:
    name: postgres

# CONFIGURATION

- name: configure repmgr
  notify: restart repmgrd
  ansible.builtin.template:
    src: repmgr.conf.j2
    dest: "{{ repmgr_conf_file }}"
    owner: postgres
    group: postgres
    mode: "644"

- name: configure debian default
  notify: restart repmgrd
  loop:
    - key: REPMGRD_ENABLED
      value: "yes"
    - key: REPMGRD_CONF
      value: "{{ repmgr_conf_file }}"
  ansible.builtin.replace:
    path: /etc/default/repmgrd
    regexp: ^#?{{ item.key }}=.*$
    replace: "{{ item.key }}={{ item.value }}"

- name: configure sudo
  ansible.builtin.copy:
    dest: /etc/sudoers.d/postgres
    validate: visudo -cf %s
    mode: "440"
    content: |
      Defaults:postgres !requiretty
      postgres ALL=NOPASSWD: \
        /bin/systemctl start postgresql@{{ repmgr_database_version }}-{{ repmgr_database_cluster }}, \
        /bin/systemctl stop postgresql@{{ repmgr_database_version }}-{{ repmgr_database_cluster }}, \
        /bin/systemctl restart postgresql@{{ repmgr_database_version }}-{{ repmgr_database_cluster }}, \
        /bin/systemctl reload postgresql@{{ repmgr_database_version }}-{{ repmgr_database_cluster }}

- name: configure swappiness
  ansible.builtin.copy:
    dest: /etc/sysctl.d/40-swappiness.conf
    owner: "root"
    group: "root"
    mode: "644"
    content: |
      # UbiCast Swappiness settings configuration for PostgreSQL on Linux

      # Parameter that controls the relative weight given to swapping out of runtime memory,
      # as opposed to dropping pages from the system page cache.
      # A low value causes the kernel to prefer to evict pages from the page cache while
      # a higher value causes the kernel to prefer to swap out "cold" memory pages.
      # Swappiness can be set to a value from 0 to 200. Default is 60.

      # See RM#38809 and https://dali.bo/j1_html#configuration-du-swap
      vm.swappiness = 10

# SSH

- name: ensure postgres account have a ssh keypair
  ansible.builtin.user:
    name: postgres
    generate_ssh_key: true
    ssh_key_type: ed25519
    ssh_key_file: ~postgres/.ssh/id_ed25519

- name: fetch postgres ssh public key
  register: repmgr_postgres_ssh_pubkey
  ansible.builtin.slurp:
    path: ~postgres/.ssh/id_ed25519.pub

- name: register postgres ssh public key as an ansible fact
  ansible.builtin.set_fact:
    pubkey: "{{ repmgr_postgres_ssh_pubkey['content'] | b64decode }}"

- name: share postgres ssh public key between cluster members
  loop: "{{ groups['postgres'] }}"
  ansible.posix.authorized_key:
    user: postgres
    key: "{{ hostvars[item]['pubkey'] }}"

- name: postgres ssh client configuration
  ansible.builtin.copy:
    dest: ~postgres/.ssh/config
    owner: postgres
    group: postgres
    mode: "640"
    content: |
      IdentityFile ~/.ssh/id_ed25519
      StrictHostKeyChecking no
      UserKnownHostsFile /dev/null

# REGISTER PRIMARY

- name: setup primary
  when: >
    (database_role is defined and database_role == "primary") or
    (database_role is undefined and inventory_hostname == groups['postgres'][0]) or
    (database_role is defined and database_role == "" and inventory_hostname == groups['postgres'][0])
  block:
    - name: check if primary already joined
      become: true
      become_user: postgres
      register: repmgr_check_primary
      community.general.postgresql_query:
        db: repmgr
        query: SELECT 1 FROM pg_tables WHERE tablename='nodes'

    - name: register primary
      become: true
      become_user: postgres
      changed_when: true
      when: repmgr_check_primary.query_result | length == 0
      notify: restart repmgrd
      ansible.builtin.command:
        cmd: repmgr --config-file={{ repmgr_conf_file }} primary register

- ansible.builtin.meta: flush_handlers # noqa name[missing]

# REGISTER STANDBY

- name: setup standby
  when: >
    (database_role is defined and database_role == "standby") or
    (database_role is undefined and inventory_hostname == groups['postgres'][1]) or
    (database_role is defined and database_role == "" and inventory_hostname == groups['postgres'][1])
  block:
    - name: check if standby already joined
      become: true
      become_user: postgres
      register: repmgr_check_standby
      community.general.postgresql_query:
        db: repmgr
        query: SELECT 1 FROM pg_tables WHERE tablename='nodes'

    - name: stop postgresql service
      when: repmgr_check_standby.query_result | length == 0
      ansible.builtin.systemd:
        name: postgresql@{{ repmgr_database_version }}-{{ repmgr_database_cluster }}
        state: stopped

    - name: remove existing pgdata
      when: repmgr_check_standby.query_result | length == 0
      ansible.builtin.command:
        cmd: mv -vf {{ repmgr_database_data_dir }} {{ repmgr_database_data_dir }}.save
        removes: "{{ repmgr_database_data_dir }}"

    - name: clone from primary to standby
      become: true
      become_user: postgres
      changed_when: true
      when: repmgr_check_standby.query_result | length == 0
      ignore_errors: true
      register: repmgr_clone_standby
      ansible.builtin.shell:
        cmd: |
          repmgr \
            --config-file={{ repmgr_conf_file }} \
            --force \
            --dbname={{ repmgr_database }} \
            --host={{ repmgr_primary_node }} \
            --port=5432 \
            --username={{ repmgr_user }} \
            --pgdata={{ repmgr_database_data_dir }} \
            standby clone --fast-checkpoint

    - name: remove pgdata backup
      when: repmgr_clone_standby is succeeded
      ansible.builtin.file:
        path: "{{ repmgr_database_data_dir }}.save"
        state: absent

    - name: remove failed clone pgdata
      when: repmgr_clone_standby is failed
      ansible.builtin.file:
        path: "{{ repmgr_database_data_dir }}"
        state: absent

    - name: restore pgdata backup
      when: repmgr_clone_standby is failed
      ansible.builtin.command:
        cmd: mv -vf {{ repmgr_database_data_dir }}.save {{ repmgr_database_data_dir }}
        removes: "{{ repmgr_database_data_dir }}.save"

    - name: start postgresql service
      ansible.builtin.systemd:
        name: postgresql@{{ repmgr_database_version }}-{{ repmgr_database_cluster }}
        state: started

    - name: standby clone failed
      when: repmgr_clone_standby is failed
      ansible.builtin.fail:
        msg: "{{ repmgr_clone_standby.stderr }}"

    - name: register standby
      become: true
      become_user: postgres
      changed_when: true
      when: repmgr_check_standby.query_result | length == 0
      notify: restart repmgrd
      ansible.builtin.command:
        cmd: repmgr --config-file={{ repmgr_conf_file }} standby register

- ansible.builtin.meta: flush_handlers # noqa name[missing]

# REGISTER WITNESS

- name: setup witness
  when: >
    (database_role is defined and database_role == "witness") or
    (database_role is undefined and inventory_hostname == groups['postgres'][2]) or
    (database_role is defined and database_role == "" and inventory_hostname == groups['postgres'][2])
  block:
    - name: check if witness already joined
      become: true
      become_user: postgres
      register: repmgr_check_witness
      community.general.postgresql_query:
        db: repmgr
        query: SELECT 1 FROM pg_tables WHERE tablename='nodes'

    - name: register witness
      become: true
      become_user: postgres
      changed_when: true
      when: repmgr_check_witness.query_result | length == 0
      notify: restart repmgrd
      ansible.builtin.command:
        cmd: repmgr --config-file={{ repmgr_conf_file }} --host={{ repmgr_primary_node }} witness register

- ansible.builtin.meta: flush_handlers # noqa name[missing]

# REPHACHECK

- name: install rephacheck
  ansible.builtin.template:
    src: rephacheck.py.j2
    dest: /usr/bin/rephacheck
    mode: "0755"

- name: register variables needed by rephacheck as facts
  ansible.builtin.set_fact:
    repmgr_node_name: "{{ repmgr_node_name }}"
    repmgr_node_id: "{{ repmgr_node_id }}"

- name: configure rephacheck
  ansible.builtin.template:
    src: rephacheck.conf.j2
    dest: /etc/postgresql/{{ repmgr_database_version }}/{{ repmgr_database_cluster }}/rephacheck.conf
    owner: postgres
    group: postgres
    mode: "0644"

- name: configure rephacheck socket
  notify:
    - reload systemd
    - restart rephacheck
  ansible.builtin.copy:
    dest: /etc/systemd/system/rephacheck.socket
    mode: "644"
    content: |
      [Unit]
      Description=RepHACheck socket

      [Socket]
      ListenStream={{ repmgr_repha_port }}
      Accept=yes

      [Install]
      WantedBy=sockets.target

- name: configure rephacheck service
  notify:
    - reload systemd
    - restart rephacheck
  ansible.builtin.copy:
    dest: /etc/systemd/system/rephacheck@.service
    mode: "644"
    content: |
      [Unit]
      Description=RepHACheck - Health check for PostgreSQL cluster managed by repmgr

      [Service]
      ExecStart=-/usr/bin/rephacheck
      StandardInput=socket
      User=postgres
      Group=postgres

- name: enable and start rephacheck
  ansible.builtin.service:
    name: rephacheck.socket
    state: started
    enabled: true

- import_tasks: ../../shared/tasks/firewall_rules_files.yml  # noqa: name[missing]

...
